-- Run with the supplied source editor, or reqscript in DFHack.
local editor=... or reqscript('df-local-zh-search-editor')
local s=editor.new('鐵𠮷A')
editor.apply(s,{kind='composition',text='ㄅㄚ',start=1,length=1})
local cursor=s.cursor
for _,kind in ipairs{'left','right','home','end','backspace','delete','select_all'} do
    assert(not editor.apply(s,{kind=kind}))
    assert(s.text=='鐵𠮷A' and s.cursor==cursor and not s.selected,'IME owns '..kind)
end
assert(s.composition=='ㄅㄚ')
editor.apply(s,{kind='composition',text=''})
editor.apply(s,{kind='backspace'})
assert(s.text=='鐵𠮷')
editor.apply(s,{kind='backspace'})
assert(s.text=='鐵','Supplementary Unicode backspace')
editor.apply(s,{kind='composition',text='ㄊㄧㄝ'})
editor.apply(s,{kind='cancel'})
assert(s.text=='鐵' and s.composition=='','Cancel preserves committed query')
editor.apply(s,{kind='select_all'})
editor.apply(s,{kind='text',text=string.char(255)})
assert(s.text=='鐵' and s.selected,'Invalid commit preserves selection and query')
editor.apply(s,{kind='text',text='鐵Ａ1𠮷'})
assert(s.text=='鐵Ａ1𠮷' and not s.selected)
assert(editor.clamp(s.text,2)==1)
local prompt=editor.new('',nil,{multiline=true,max_bytes=32768})
editor.apply(prompt,{kind='text',text='提示詞\n第二行𠮷'})
assert(prompt.text=='提示詞\n第二行𠮷')
local bounded=editor.new('原文',nil,{multiline=true,max_bytes=32768,max_chars=8192})
editor.apply(bounded,{kind='text',text=string.rep('A',8192)})
assert(bounded.text=='原文','Character limit must preserve draft')
editor.apply(bounded,{kind='text',text='\r\n𠮷'})
assert(bounded.text=='原文\n𠮷','Windows multiline paste must normalize CRLF')
local secret=editor.new('fixture',nil,{secret=true,max_bytes=8192})
editor.apply(secret,{kind='select_all'})
assert(not editor.apply(secret,{kind='text',text='中文'}) and secret.text=='fixture')
editor.apply(secret,{kind='text',text='fixture-key'})
assert(secret.text=='fixture-key')
local copied=editor.new('好郝𠮷gjsok184')
editor.apply(copied,{kind='select_all'})
local text,from,to=editor.clipboard_range(copied)
assert(text==copied.text and from==1 and to==#copied.text+1,'Ctrl+A copy must keep exact UTF-8')
assert(editor.cut_range(copied,from,to) and copied.text=='','Cut clears only after a successful clipboard write')
editor.apply(copied,{kind='text',text=text})
assert(copied.text=='好郝𠮷gjsok184','Copy/cut/paste roundtrip must keep Chinese and supplementary Unicode')
copied.cursor=8
text,from,to=editor.clipboard_range(copied,5)
assert(text=='郝𠮷' and from==4 and to==11,'Reversed mouse selection must include whole Unicode characters')
assert(editor.cut_range(copied,from,to) and copied.text=='好gjsok184')
assert(editor.clipboard_range(secret)==nil,'Masked field must not export a secret')
editor.apply(copied,{kind='composition',text='ㄅ'})
assert(editor.clipboard_range(copied)==nil,'Composition belongs to Windows even during copy')
local lines=editor.new('第一行\n第二行',nil,{multiline=true,max_bytes=32768})
text,from,to=editor.clipboard_range(lines)
assert(text=='第二行\n' and from==11 and to==#lines.text+1,'No-selection multiline copy preserves current-line semantics')
local candidates=editor.candidate_line{active=true,first=0,selected=0,items={'一','壹'}}
assert(candidates=='候選 >1:一  2:壹','Candidate line preserves the selected item')
assert(editor.candidate_line{active=false,items={'一'}}==nil,'Inactive candidates stay hidden')
local function columns(text)
    local count=0
    for _,code in utf8.codes(text) do count=count+(code>=0x2e80 and 2 or 1) end
    return count
end
local box=editor.candidate_box({active=true,first=9,selected=10,items={'甲','乙','丙'}},20,8,19,7,columns)
assert(box and box.x>=0 and box.x+box.width<=20,'Candidate box must stay inside the screen width')
assert(box.y>=0 and box.y+3<=8,'Candidate box must move above a bottom-edge field')
assert(box.line:find('>2:乙',1,true),'Clipping must retain the selected OS candidate')
assert(columns(box.line)<=box.width-2,'Candidate text must fit inside the border')
assert(editor.candidate_box({active=false,items={'甲'}},20,8,0,0,columns)==nil)
assert(editor.candidate_box({active=true,first=0,selected=0,items={'甲'}},4,2,0,0,columns)==nil,'Tiny surfaces must not draw outside their bounds')
print('IME_EDITOR passed')
