local editor=reqscript('df-local-zh-search-editor')
local native=reqscript('df-local-zh-core/native')
local function check(value,message) assert(value,message) end
local state=editor.new('鐵高腳杯')
editor.apply(state,{kind='left'})
editor.apply(state,{kind='backspace'})
check(state.text=='鐵高杯','UTF-8 backspace must remove one character')
editor.apply(state,{kind='delete'})
check(state.text=='鐵高','UTF-8 delete must remove one character')
editor.apply(state,{kind='select_all'})
editor.apply(state,{kind='text',text='花崗岩'})
check(state.text=='花崗岩','Replace selection with Chinese text')
editor.apply(state,{kind='composition',text='hua'})
check(state.text=='花崗岩' and state.composition=='hua','IME composition must not filter before commit')
check(native.search_matches('iron goblet','鐵'),'Chinese iron match')
check(native.search_matches('iron goblet','高腳杯'),'Chinese goblet match')
check(native.search_matches('granite blocks','花崗岩'),'Chinese granite match')
check(not native.search_matches('granite blocks','鐵'),'Exclude unrelated materials')
print('CHINESE_SEARCH_UNIT passed=9')
