base = "gems"

[[rulesets]]
[rulesets.rules]
"{singular}" = "{singular}"
"{plural}" = "{plural}"

[[rulesets]]
name = "singular"

  [rulesets.rules]
  "{materials::singular}" = "{materials::singular}"
  "{::materials}" = "{::materials}"

[[rulesets]]
name = "plural"

  [rulesets.rules]
  "{materials::plural}" = "{materials::plural}"
  "{::materials}" = "{::materials}"

[[rulesets]]
name = "materials::singular"

  [rulesets.rules]
  onyx = "縞瑪瑙"
  morion = "黑水晶"
  schorl = "黑碧璽"
  "lace agate" = "蕾絲瑪瑙"
  "blue jade" = "藍翡翠"
  "lapis lazuli" = "青金石"
  prase = "蒼綠石英"
  "prase opal" = "蒼綠歐泊"
  bloodstone = "血石"
  "moss agate" = "苔蘚瑪瑙"
  "moss opal" = "苔蘚歐泊"
  variscite = "磷鋁石"
  chrysoprase = "綠玉髓"
  chrysocolla = "矽孔雀石"
  sard = "褐玉髓"
  carnelian = "紅玉髓"
  "banded agate" = "條紋瑪瑙"
  sardonyx = "纏絲瑪瑙"
  "cherry opal" = "櫻桃歐泊"
  "lavender jade" = "紫翡翠"
  "pink jade" = "粉紅翡翠"
  "tube agate" = "管脈瑪瑙"
  "fire agate" = "火瑪瑙"
  "plume agate" = "羽毛瑪瑙"
  "brown jasper" = "棕碧玉"
  "picture jasper" = "圖畫碧玉"
  "smoky quartz" = "煙石英"
  "wax opal" = "蠟質歐泊"
  "wood opal" = "木歐泊"
  "amber opal" = "琥珀歐泊"
  "gold opal" = "金歐泊"
  citrine = "黃水晶"
  "yellow jasper" = "黃碧玉"
  tigereye = "虎眼石"
  "tiger iron" = "虎鐵石"
  sunstone = "日長石"
  "resin opal" = "脂光歐泊"
  pyrite = "黃鐵礦"
  "clear tourmaline" = "透明碧璽"
  "gray chalcedony" = "灰玉髓"
  "dendritic agate" = "枝紋瑪瑙"
  "shell opal" = "貝殼歐泊"
  "bone opal" = "骨質歐泊"
  "white chalcedony" = "白玉髓"
  "fortification agate" = "城壘瑪瑙"
  "milk quartz" = "乳石英"
  moonstone = "月長石"
  "white jade" = "白翡翠"
  "jasper opal" = "碧玉歐泊"
  "pineapple opal" = "鳳梨歐泊"
  "onyx opal" = "縞紋歐泊"
  "milk opal" = "乳歐泊"
  "pipe opal" = "管紋歐泊"
  aventurine = "砂金石"
  turquoise = "綠松石"
  "rose quartz" = "薔薇石英"
  "rock crystal" = "岩石水晶"
  "black zircon" = "黑鋯石"
  "black pyrope" = "黑榴石"
  melanite = "墨榴石"
  "indigo tourmaline" = "靛藍碧璽"
  "blue garnet" = "藍榴石"
  tsavorite = "沙弗萊石"
  "green tourmaline" = "綠碧璽"
  demantoid = "翠榴石"
  "green zircon" = "綠鋯石"
  "green jade" = "綠翡翠"
  heliodor = "綠柱石"
  peridot = "橄欖石"
  "red zircon" = "紅鋯石"
  "red tourmaline" = "紅碧璽"
  "red pyrope" = "赤榴石"
  almandine = "殷榴石"
  "red grossular" = "紅榴石"
  "pink tourmaline" = "粉紅碧璽"
  "red beryl" = "紅柱石"
  "fire opal" = "火歐泊"
  rhodolite = "朱榴石"
  "purple spinel" = "紫尖晶石"
  alexandrite = "紫翠玉"
  tanzanite = "坦桑石"
  morganite = "摩根石"
  "violet spessartine" = "紫榴石"
  "pink garnet" = "粉紅榴石"
  kunzite = "紫鋰輝石"
  "cinnamon grossular" = "褐榴石"
  "honey yellow beryl" = "蜜黃柱石"
  "jelly opal" = "凍膠歐泊"
  "brown zircon" = "棕鋯石"
  "yellow zircon" = "黃鋯石"
  "golden beryl" = "金柱石"
  "yellow spessartine" = "橙榴石"
  topaz = "黃玉"
  topazolite = "黃榴石"
  "yellow grossular" = "緗榴石"
  rubicelle = "橙尖晶石"
  "clear garnet" = "透明榴石"
  goshenite = "白柱石"
  "cat's eye" = "貓眼石"
  "clear zircon" = "透明鋯石"
  amethyst = "紫水晶"
  aquamarine = "海藍寶石"
  "red spinel" = "紅尖晶石"
  chrysoberyl = "金綠玉"
  "precious fire opal" = "貴火歐泊"
  "red flash opal" = "紅閃歐泊"
  "black opal" = "黑歐泊"
  "white opal" = "白歐泊"
  "crystal opal" = "水晶歐泊"
  "claro opal" = "煙歐泊"
  "levin opal" = "雷電歐泊"
  "harlequin opal" = "斑斕歐泊"
  "pinfire opal" = "星火歐泊"
  "bandfire opal" = "火紋歐泊"
  "light yellow diamond" = "亮黃鑽石"
  "faint yellow diamond" = "微黃鑽石"
  emerald = "祖母綠寶石"
  ruby = "紅寶石"
  sapphire = "藍玉"
  "clear diamond" = "透明鑽石"
  "red diamond" = "紅鑽石"
  "green diamond" = "綠鑽石"
  "blue diamond" = "藍鑽石"
  "yellow diamond" = "黃鑽石"
  "black diamond" = "黑鑽石"
  "star sapphire" = "星彩藍玉"
  "star ruby" = "星彩紅寶石"

[[rulesets]]
name = "materials::plural"

  [rulesets.rules]
  onyxes = "縞瑪瑙"
  morions = "黑水晶"
  schorls = "黑碧璽"
  "lace agates" = "蕾絲瑪瑙"
  "blue jades" = "藍翡翠"
  "lapis lazulis" = "青金石"
  prases = "蒼綠石英"
  "prase opals" = "蒼綠歐泊"
  bloodstones = "血石"
  "moss agates" = "苔蘚瑪瑙"
  "moss opals" = "苔蘚歐泊"
  variscites = "磷鋁石"
  chrysoprases = "綠玉髓"
  chrysocollas = "矽孔雀石"
  sards = "褐玉髓"
  carnelians = "紅玉髓"
  "banded agates" = "條紋瑪瑙"
  sardonyxes = "纏絲瑪瑙"
  "cherry opals" = "櫻桃歐泊"
  "lavender jades" = "紫翡翠"
  "pink jades" = "粉紅翡翠"
  "tube agates" = "管脈瑪瑙"
  "fire agates" = "火瑪瑙"
  "plume agates" = "羽毛瑪瑙"
  "brown jaspers" = "棕碧玉"
  "picture jaspers" = "圖畫碧玉"
  "smoky quartzes" = "煙石英"
  "wax opals" = "蠟質歐泊"
  "wood opals" = "木歐泊"
  "amber opals" = "琥珀歐泊"
  "gold opals" = "金歐泊"
  citrines = "黃水晶"
  "yellow jaspers" = "黃碧玉"
  tigereyes = "虎眼石"
  "tiger irons" = "虎鐵石"
  sunstones = "日長石"
  "resin opals" = "脂光歐泊"
  pyrites = "黃鐵礦"
  "clear tourmalines" = "透明碧璽"
  "gray chalcedonies" = "灰玉髓"
  "dendritic agates" = "枝紋瑪瑙"
  "shell opals" = "貝殼歐泊"
  "bone opals" = "骨質歐泊"
  "white chalcedonies" = "白玉髓"
  "fortification agates" = "城壘瑪瑙"
  "milk quartzes" = "乳石英"
  moonstones = "月長石"
  "white jades" = "白翡翠"
  "jasper opals" = "碧玉歐泊"
  "pineapple opals" = "鳳梨歐泊"
  "onyx opals" = "縞紋歐泊"
  "milk opals" = "乳歐泊"
  "pipe opals" = "管紋歐泊"
  aventurines = "砂金石"
  turquoises = "綠松石"
  "rose quartzes" = "薔薇石英"
  "rock crystals" = "岩石水晶"
  "black zircons" = "黑鋯石"
  "black pyropes" = "黑榴石"
  melanites = "墨榴石"
  "indigo tourmalines" = "靛藍碧璽"
  "blue garnets" = "藍榴石"
  tsavorites = "沙弗萊石"
  "green tourmalines" = "綠碧璽"
  demantoids = "翠榴石"
  "green zircons" = "綠鋯石"
  "green jades" = "綠翡翠"
  heliodors = "綠柱石"
  peridots = "橄欖石"
  "red zircons" = "紅鋯石"
  "red tourmalines" = "紅碧璽"
  "red pyropes" = "赤榴石"
  almandines = "殷榴石"
  "red grossulars" = "紅榴石"
  "pink tourmalines" = "粉紅碧璽"
  "red beryls" = "紅柱石"
  "fire opals" = "火歐泊"
  rhodolites = "朱榴石"
  "purple spinels" = "紫尖晶石"
  alexandrites = "紫翠玉"
  tanzanites = "坦桑石"
  morganites = "摩根石"
  "violet spessartines" = "紫榴石"
  "pink garnets" = "粉紅榴石"
  kunzites = "紫鋰輝石"
  "cinnamon grossulars" = "褐榴石"
  "honey yellow beryls" = "蜜黃柱石"
  "jelly opals" = "凍膠歐泊"
  "brown zircons" = "棕鋯石"
  "yellow zircons" = "黃鋯石"
  "golden beryls" = "金柱石"
  "yellow spessartines" = "橙榴石"
  topazes = "黃玉"
  topazolites = "黃榴石"
  "yellow grossulars" = "緗榴石"
  rubicelles = "橙尖晶石"
  "clear garnets" = "透明榴石"
  goshenites = "白柱石"
  "cat's eyes" = "貓眼石"
  "clear zircons" = "透明鋯石"
  amethysts = "紫水晶"
  aquamarines = "海藍寶石"
  "red spinels" = "紅尖晶石"
  chrysoberyls = "金綠玉"
  "precious fire opals" = "貴火歐泊"
  "red flash opals" = "紅閃歐泊"
  "black opals" = "黑歐泊"
  "white opals" = "白歐泊"
  "crystal opals" = "水晶歐泊"
  "claro opals" = "煙歐泊"
  "levin opals" = "雷電歐泊"
  "harlequin opals" = "斑斕歐泊"
  "pinfire opals" = "星火歐泊"
  "bandfire opals" = "火紋歐泊"
  "light yellow diamonds" = "亮黃鑽石"
  "faint yellow diamonds" = "微黃鑽石"
  emeralds = "祖母綠寶石"
  rubies = "紅寶石"
  sapphires = "藍玉"
  "clear diamonds" = "透明鑽石"
  "red diamonds" = "紅鑽石"
  "green diamonds" = "綠鑽石"
  "blue diamonds" = "藍鑽石"
  "yellow diamonds" = "黃鑽石"
  "black diamonds" = "黑鑽石"
  "star sapphires" = "星彩藍玉"
  "star rubies" = "星彩紅寶石"
