base = "materials::state"

[[rulesets]]
[rulesets.rules]
"gold dust" = "金粉"
metal = "金屬"
"native gold dust" = "天然金粉"
fat = "脂肪"
grease = "油脂"
cartilage = "軟骨"
cheese = "乳酪"
wood = "木頭"
sponge = "海綿"
"saguaro rib wood" = "巨刺柱肋木"
oak = "橡樹"
birch = "樺樹"
"{shared}" = "{shared}"
"flux stone layer" = "熔劑石層"

[[rulesets]]
name = "adjective"

  [rulesets.rules]
  fatty = "脂肪"
  greasy = "油脂"
  cartilaginous = "軟骨"
  cheesy = "乳酪"
  wooden = "木製"
  spongy = "海綿"
  "saguaro rib" = "巨刺柱肋木"
  oaken = "橡木"
  birchen = "白樺木"
  ashen = "白蠟木"
  "{shared}" = "{shared}"

[[rulesets]]
name = "shared"

  [rulesets.rules]
  "{shared::^0}{shared::main}{shared::$0}" = "{shared::^0}{shared::main}{shared::$0}"

[[rulesets]]
name = "shared::^0"
optional = true

  [rulesets.rules]
  "boiling " = "沸騰"
  "ground " = "磨碎的"
  "pressed " = "壓制"
  "molten " = "融化的"
  "frozen " = "結凍"
  "melted " = "熔融"

[[rulesets]]
name = "shared::main"

  [rulesets.rules]
  acacia = "刺槐"
  adamantine = "精金"
  "adder man venom" = "蝰蛇人毒素"
  "adder venom" = "蝰蛇毒素"
  alabaster = "雪花石膏"
  alder = "榿樹"
  alexandrite = "紫翠玉"
  almandine = "殷榴石"
  "almond wood" = "扁桃木"
  "alpaca cheese" = "羊駝乳酪"
  "alpaca's milk" = "羊駝奶"
  aluminum = "鋁"
  alunite = "明礬石"
  amber = "琥珀"
  "amber opal" = "琥珀歐泊"
  amethyst = "紫水晶"
  andesite = "安山岩"
  anhydrite = "硬石膏"
  antler = "鹿角"
  "apple cider" = "蘋果西打"
  "apple wood" = "蘋果木"
  "apricot wine" = "杏酒"
  "apricot wood" = "杏木"
  aquamarine = "海藍寶石"
  "artichoke wine" = "洋薊酒"
  ash = "灰燼"
  "ash glaze" = "灰釉"
  aventurine = "砂金石"
  "avocado wood" = "鱷梨木"
  "banana beer" = "香蕉啤酒"
  "banded agate" = "條紋瑪瑙"
  "bandfire opal" = "火紋歐泊"
  "bark scorpion man venom" = "樹皮蠍人毒素"
  "bark scorpion venom" = "樹皮蠍毒素"
  "barley flour" = "大麥麵粉"
  "barley wine" = "大麥酒"
  basalt = "玄武岩"
  bauxite = "鋁土礦"
  "bayberry wine" = "楊梅酒"
  "bayberry wood" = "楊梅木"
  "beetroot wine" = "甜菜根酒"
  "bilberry wine" = "越橘酒"
  billon = "畢朗合金"
  bismuth = "鉍"
  "bismuth bronze" = "鉍青銅"
  bismuthinite = "輝鉍礦"
  "bitter orange wood" = "苦橙木"
  "bituminous coal" = "煙煤"
  "blackberry wine" = "黑莓酒"
  "black bronze" = "烏青銅"
  black-cap = "黑菇"
  "black diamond" = "黑鑽石"
  "black mamba man venom" = "黑曼巴蛇人毒素"
  "black mamba venom" = "黑曼巴蛇毒素"
  "black opal" = "黑歐泊"
  "black pyrope" = "黑榴石"
  "black sand" = "黑沙"
  "black zircon" = "黑鋯石"
  blood = "血液"
  "blood amaranth beer" = "血莧啤酒"
  "blood amaranth flour" = "血莧麵粉"
  bloodstone = "血石"
  "blood thorn" = "血荊棘"
  "blueberry wine" = "藍莓酒"
  "blue diamond" = "藍鑽石"
  "blue garnet" = "藍榴石"
  "blue jade" = "藍翡翠"
  bone = "骨頭"
  "bone meal" = "骨粉"
  "bone opal" = "骨質歐泊"
  borax = "硼砂"
  brain = "大腦"
  brass = "黃銅"
  brimstone = "硫磺"
  bronze = "青銅"
  "brown jasper" = "棕碧玉"
  "brown recluse spider man venom" = "棕色遁蛛人毒素"
  "brown recluse spider venom" = "棕色遁蛛毒素"
  "brown zircon" = "棕鋯石"
  "buckwheat beer" = "蕎麥啤酒"
  "buckwheat flour" = "蕎麥麵粉"
  bud = "花蕾"
  "bumblebee honey" = "大黃蜂蜜"
  "bumblebee mead" = "大黃蜂蜜酒"
  "bumblebee royal jelly" = "大黃蜂蜂王漿"
  "bumblebee venom" = "大黃蜂毒素"
  "bumblebee wax" = "大黃蜂蠟"
  "bumblebee wax cake" = "大黃蜂蠟餅"
  "bushmaster man venom" = "巨蝮人毒素"
  "bushmaster venom" = "巨蝮毒素"
  "cacao wood" = "可可樹"
  "calcareous ooze" = "鈣質軟泥"
  calcite = "方解石"
  candlenut = "石栗"
  "carambola wine" = "楊桃酒"
  "carambola wood" = "楊桃木"
  carnelian = "紅玉髓"
  "carrot wine" = "胡蘿蔔酒"
  "cashew wood" = "腰果木"
  "cassava beer" = "木薯啤酒"
  cassiterite = "錫石"
  "cat's eye" = "貓眼石"
  "cave blob fluid" = "洞穴滴團液體"
  "cave floater gas" = "洞穴飄浮者氣體"
  "cave floater juice" = "洞穴飄浮者汁液"
  "cave spider venom" = "洞穴蜘蛛毒素"
  cedar = "雪松"
  chalk = "白堊巖"
  "cherry opal" = "櫻桃歐泊"
  "cherry wine" = "櫻桃酒"
  "cherry wood" = "櫻桃木"
  chert = "角巖"
  chestnut = "板栗樹"
  chitin = "甲殼"
  chromite = "鉻鐵礦"
  chrysoberyl = "金綠玉"
  chrysocolla = "矽孔雀石"
  chrysoprase = "綠玉髓"
  cinnabar = "辰砂"
  "cinnamon grossular" = "褐榴石"
  citrine = "黃水晶"
  "citron wood" = "香櫞木"
  "claro opal" = "煙歐泊"
  clay = "黏土"
  "clay loam" = "黏質壤土"
  claystone = "黏土巖"
  "clear diamond" = "透明鑽石"
  "clear garnet" = "透明榴石"
  "clear glass" = "透明玻璃"
  "clear tourmaline" = "透明碧璽"
  "clear zircon" = "透明鋯石"
  coal = "煤炭"
  "coal slush" = "煤炭渣"
  cobaltite = "輝鈷礦"
  "coconut palm" = "椰棕櫚"
  "coffee wood" = "咖啡木"
  "condensed iron man gas" = "稠密鐵人氣體"
  conglomerate = "礫岩"
  copper = "銅"
  "copperhead snake man venom" = "銅頭蛇人毒素"
  "copperhead snake venom" = "銅頭蛇毒素"
  coral = "珊瑚"
  "corrupted blood" = "腐敗血液"
  cotton = "棉花"
  "cotton seed" = "棉花種子"
  "cottonseed oil" = "棉花籽油"
  "cottonseed oil soap" = "棉花籽油肥皂"
  "cow cheese" = "牛奶乳酪"
  "cow's milk" = "牛奶"
  "cranberry wine" = "蔓越莓酒"
  cryolite = "冰晶石"
  "crystal glass" = "水晶玻璃"
  "crystal opal" = "水晶歐泊"
  "custard-apple cider" = "番荔枝西打"
  "custard-apple wood" = "番荔枝木"
  "cuttlefish ink" = "墨魚墨汁"
  "cuttlefish man ink" = "墨魚人墨汁"
  dacite = "英安巖"
  "date palm wood" = "椰棗棕櫚木"
  "date wine" = "椰棗酒"
  demantoid = "翠榴石"
  "dendritic agate" = "枝紋瑪瑙"
  "desert lime wood" = "漠橘木"
  "dimple dye" = "窩杯染料"
  diorite = "閃長巖"
  dirt = "土壤"
  dolomite = "白雲石"
  "donkey cheese" = "驢奶乳酪"
  "donkey's milk" = "驢奶"
  "durian wine" = "榴槤酒"
  "durian wood" = "榴槤木"
  "dwarven ale" = "矮人精釀"
  "dwarven beer" = "矮人麥啤"
  "dwarven cheese" = "矮人乳酪"
  "dwarven milk" = "矮人奶"
  "dwarven rum" = "矮人朗姆酒"
  "dwarven sugar" = "矮人砂糖"
  "dwarven syrup" = "矮人糖漿"
  "dwarven wheat flour" = "矮人小麥粉"
  "dwarven wine" = "矮人酒"
  earthenware = "瓦陶"
  eggshell = "蛋殼"
  "egg white" = "蛋白"
  "egg yolk" = "蛋黃"
  electrum = "琥珀金"
  emerald = "祖母綠寶石"
  "emerald dye" = "寶石綠染料"
  "eye tissue" = "眼部組織"
  "faint yellow diamond" = "微黃鑽石"
  feather = "羽毛"
  "feather wood" = "羽毛樹"
  fiber = "纖維"
  filth = "汙垢"
  "filth slush" = "汙垢泥"
  "fine pewter" = "精白錫"
  "finger lime wood" = "指橘木"
  "finger millet beer" = "爪粟啤酒"
  "finger millet flour" = "爪粟麵粉"
  "fire agate" = "火瑪瑙"
  "fire clay" = "火黏土"
  "fire opal" = "火歐泊"
  "fisher berry wine" = "漁夫漿果酒"
  flames = "火焰"
  "flax flour" = "亞麻麵粉"
  "flax seed" = "亞麻種子"
  flesh = "血肉"
  flower = "花"
  fluff = "絨毛"
  "fonio beer" = "非尼奧啤酒"
  "fonio flour" = "非尼奧麵粉"
  "fortification agate" = "城壘瑪瑙"
  "foxtail millet beer" = "狐尾粟啤酒"
  "foxtail millet flour" = "狐尾粟麵粉"
  fruit = "果實"
  fungiwood = "真菌木"
  fur = "毛皮"
  gabbro = "輝長岩"
  galena = "方鉛礦"
  garnierite = "矽鎂鎳礦"
  "giant adder venom" = "巨型蝰蛇毒素"
  "giant bark scorpion venom" = "巨型樹皮蠍毒素"
  "giant black mamba venom" = "巨型黑曼巴蛇毒素"
  "giant brown recluse spider venom" = "巨型棕色遁蛛毒素"
  "giant bushmaster venom" = "巨型巨蝮毒素"
  "giant cave spider venom" = "巨型洞穴蜘蛛毒素"
  "giant copperhead snake venom" = "巨型銅頭蛇毒素"
  "giant cuttlefish ink" = "巨型墨魚墨汁"
  "giant gila monster venom" = "巨型毒蜥毒素"
  "giant kangaroo cheese" = "巨型袋鼠乳酪"
  "giant kangaroo's milk" = "巨型袋鼠奶"
  "giant king cobra venom" = "巨型眼鏡王蛇毒素"
  "giant octopus ink" = "巨型章魚墨汁"
  "giant one-humped camel cheese" = "巨型單峰駱駝乳酪"
  "giant one-humped camel's milk" = "巨型單峰駱駝奶"
  "giant platypus venom" = "巨型鴨嘴獸毒素"
  "giant rattlesnake venom" = "巨型響尾蛇毒素"
  "giant squid ink" = "巨型魷魚墨汁"
  "giant tapir cheese" = "巨型貘乳酪"
  "giant tapir's milk" = "巨型貘奶"
  "giant two-humped camel cheese" = "巨型雙峰駱駝乳酪"
  "giant two-humped camel's milk" = "巨型雙峰駱駝奶"
  "gila monster man venom" = "毒蜥人毒素"
  "gila monster venom" = "毒蜥毒素"
  "ginkgo wood" = "銀杏木"
  "gizzard tissue" = "砂囊組織"
  glumprong = "紫影樹"
  gneiss = "片麻岩"
  gnomeblight = "地精枯萎病"
  "goat cheese" = "山羊奶乳酪"
  "goat's milk" = "山羊奶"
  goblin-cap = "妖精菇"
  gold = "金"
  "golden beryl" = "金柱石"
  "golden salve" = "金色藥膏"
  "gold opal" = "金歐泊"
  goo = "稠血"
  goshenite = "白柱石"
  granite = "花崗岩"
  graphite = "石墨"
  "gray chalcedony" = "灰玉髓"
  "green diamond" = "綠鑽石"
  "green glass" = "綠玻璃"
  "green jade" = "綠翡翠"
  "green tourmaline" = "綠碧璽"
  "green zircon" = "綠鋯石"
  grime = "塵垢"
  "guava wine" = "番石榴酒"
  "guava wood" = "番石榴木"
  gut = "腸"
  "gutter cruor" = "凝血酒"
  gypsum = "軟石膏"
  "gypsum plaster" = "石膏灰泥"
  hair = "毛髮"
  "hard wheat beer" = "硬質小麥啤"
  "hard wheat flour" = "硬質小麥麵粉"
  "harlequin opal" = "斑斕歐泊"
  "hazel wood" = "榛木"
  "heart tissue" = "心臟組織"
  heliodor = "綠柱石"
  "helmet snake venom" = "頭盔蛇毒素"
  hematite = "赤鐵礦"
  hemp = "大麻"
  "hemp flour" = "大麻麵粉"
  "hemp seed" = "大麻種子"
  "hempseed oil" = "大麻籽油"
  "hempseed oil soap" = "大麻籽油肥皂"
  highwood = "極樹"
  "honey bee honey" = "蜜蜂蜜"
  "honey bee royal jelly" = "蜜蜂蜂王漿"
  "honey bee venom" = "蜜蜂毒素"
  "honey bee wax" = "蜂蠟"
  "honey bee wax cake" = "蜂蠟餅"
  "honey yellow beryl" = "蜜黃柱石"
  hoof = "蹄"
  horn = "角"
  hornblende = "角閃石"
  "horn silver" = "角銀礦"
  "horse cheese" = "馬奶乳酪"
  "horse's milk" = "馬奶"
  ice = "冰"
  ichor = "體液"
  ilmenite = "鈦鐵礦"
  "indigo tourmaline" = "靛藍碧璽"
  iron = "鐵"
  "iron man gas" = "鐵人氣體"
  ivory = "長牙"
  "jasper opal" = "碧玉歐泊"
  "jelly opal" = "凍膠歐泊"
  jet = "煤玉"
  jute = "黃麻纖維"
  "kangaroo cheese" = "袋鼠乳酪"
  "kangaroo man cheese" = "袋鼠人乳酪"
  "kangaroo man's milk" = "袋鼠人奶"
  "kangaroo's milk" = "袋鼠奶"
  "kaniwa beer" = "彩藜啤酒"
  "kaniwa flour" = "彩藜麵粉"
  kaolinite = "高嶺石"
  kapok = "木棉樹"
  kenaf = "洋麻"
  "kenaf seed" = "洋麻種子"
  "kenaf seed oil" = "洋麻籽油"
  "kenaf seed oil soap" = "洋麻籽油肥皂"
  "kidney tissue" = "腎組織"
  kimberlite = "金伯利岩"
  "king cobra man venom" = "眼鏡王蛇人毒素"
  "king cobra venom" = "眼鏡王蛇毒素"
  "kumquat wood" = "金橘木"
  kunzite = "紫鋰輝石"
  "lace agate" = "蕾絲瑪瑙"
  "lapis lazuli" = "青金石"
  larch = "落葉松"
  "lavender jade" = "紫翡翠"
  "lay pewter" = "劣白錫"
  lead = "鉛"
  leaf = "葉"
  leather = "皮革"
  "levin opal" = "雷電歐泊"
  "light yellow diamond" = "亮黃鑽石"
  lignite = "褐煤"
  limestone = "石灰岩"
  "lime wood" = "酸橙木"
  limonite = "褐鐵礦"
  linen = "亞麻纖維"
  "linseed oil" = "亞麻籽油"
  "linseed oil soap" = "亞麻籽油肥皂"
  "liquid fire" = "液態火焰"
  "liver tissue" = "肝臟組織"
  "llama cheese" = "無峰駝乳酪"
  "llama's milk" = "無峰駝奶"
  loam = "壤土"
  "loamy sand" = "壤砂"
  "Longland beer" = "長島啤酒"
  "Longland flour" = "長島草麵粉"
  "lung tissue" = "肺部組織"
  "lychee wine" = "荔枝酒"
  "lychee wood" = "荔枝木"
  lye = "鹼液"
  "lye slush" = "鹼液泥"
  "macadamia wood" = "奶油果木"
  magma = "岩漿"
  magnetite = "磁鐵礦"
  mahogany = "褐芯樹"
  "maize beer" = "玉米啤酒"
  "maize flour" = "玉米麵粉"
  malachite = "孔雀石"
  "mango wine" = "芒果酒"
  "mango wood" = "芒果樹"
  mangrove = "紅樹"
  maple = "楓樹"
  marble = "大理石"
  marcasite = "白鐵礦"
  mead = "蜜酒"
  melanite = "墨榴石"
  mica = "雲母"
  microcline = "微斜長石"
  "milk of lime" = "石灰乳"
  "milk opal" = "乳歐泊"
  "milk quartz" = "乳石英"
  "mog juice" = "跳蟲肉汁"
  moonstone = "月長石"
  morganite = "摩根石"
  morion = "黑水晶"
  "moss agate" = "苔蘚瑪瑙"
  "moss opal" = "苔蘚歐泊"
  mud = "淤泥"
  mudstone = "泥岩"
  muscle = "肌肉"
  mushroom = "蘑菇"
  nail = "指甲"
  "native aluminum" = "天然鋁礦"
  "native copper" = "天然銅礦"
  "native gold" = "天然金礦"
  "native platinum" = "天然鉑礦"
  "native silver" = "天然銀礦"
  "nervous tissue" = "神經組織"
  nether-cap = "下界菇"
  nickel = "鎳"
  "nickel silver" = "鎳銀"
  "oat flour" = "燕麥麵粉"
  obsidian = "黑曜石"
  "octopus ink" = "章魚墨汁"
  "octopus man ink" = "章魚人墨汁"
  "olive fruit" = "橄欖果"
  "olive oil" = "橄欖油"
  "olive oil soap" = "橄欖油皂"
  "olive pomace" = "橄欖果渣"
  "olive wood" = "橄欖木"
  olivine = "橄欖岩"
  "one-humped camel cheese" = "單峰駱駝乳酪"
  "one-humped camel man cheese" = "單峰駱駝人乳酪"
  "one-humped camel man's milk" = "單峰駱駝人奶"
  "one-humped camel's milk" = "單峰駱駝奶"
  onyx = "縞瑪瑙"
  "onyx opal" = "縞紋歐泊"
  "orange wood" = "橘子木"
  orpiment = "雌黃"
  orthoclase = "正長石"
  "pancreatic tissue" = "胰臟組織"
  "papaya wine" = "番木瓜酒"
  "papaya wood" = "番木瓜木"
  papyrus = "紙莎草"
  "paradise nut wood" = "天堂果木"
  parchment = "羊皮紙"
  "parsnip wine" = "防風草酒"
  "passion fruit wine" = "百香果酒"
  "peach cider" = "桃子西打"
  "peach wood" = "桃木"
  pearlash = "珍珠灰"
  "pearl millet beer" = "珍珠粟啤酒"
  "pearl millet flour" = "珍珠粟麵粉"
  "pear wood" = "梨木"
  peat = "泥炭"
  "pecan wood" = "碧根果木"
  "pelagic clay" = "深海黏土"
  "pendant amaranth beer" = "吊墜莧啤酒"
  "pendant amaranth flour" = "吊墜莧麵粉"
  periclase = "方鎂石"
  peridot = "橄欖石"
  perry = "梨酒"
  "persimmon wine" = "柿酒"
  "persimmon wood" = "柿木"
  "petrified wood" = "石化木"
  "phantom spider venom" = "幻影蜘蛛毒素"
  phyllite = "千枚巖"
  "picture jasper" = "圖畫碧玉"
  "pig cheese" = "豬奶乳酪"
  "pig iron" = "生鐵"
  "pig's milk" = "豬奶"
  "pig tail" = "豬尾草"
  pine = "針松"
  "pineapple opal" = "鳳梨歐泊"
  "pineapple wine" = "菠蘿酒"
  "pinfire opal" = "星火歐泊"
  "pink garnet" = "粉紅榴石"
  "pink jade" = "粉紅翡翠"
  "pink tourmaline" = "粉紅碧璽"
  "pipe opal" = "管紋歐泊"
  pitchblende = "瀝青鈾礦"
  plant = "植物"
  platinum = "鉑"
  "platypus man venom" = "鴨嘴獸人毒素"
  "platypus venom" = "鴨嘴獸毒素"
  "plume agate" = "羽毛瑪瑙"
  "plump helmet man tissue" = "肉盔菇人組織"
  "plum wine" = "李子酒"
  "plum wood" = "李子木"
  "pomegranate wine" = "石榴酒"
  "pomegranate wood" = "石榴木"
  "pomelo wood" = "蜜柚木"
  porcelain = "瓷器"
  potash = "草鹼"
  "potash slush" = "草鹼渣"
  "potato wine" = "馬鈴薯酒"
  prase = "蒼綠石英"
  "prase opal" = "蒼綠歐泊"
  "precious fire opal" = "貴火歐泊"
  "prickle berry wine" = "刺莓酒"
  puddingstone = "布丁巖"
  pudge = "球脂"
  "purple amaranth beer" = "紫莧啤酒"
  "purple amaranth flour" = "紫莧麵粉"
  "purple spinel" = "紫尖晶石"
  pus = "膿"
  pyrite = "黃鐵礦"
  pyrolusite = "軟錳礦"
  quartzite = "石英岩"
  quicklime = "生石灰"
  "quinoa beer" = "藜麥啤酒"
  "quinoa flour" = "藜麥麵粉"
  "radish wine" = "小蘿蔔酒"
  "rambutan wine" = "紅毛丹酒"
  "rambutan wood" = "紅毛丹木"
  ramie = "苧麻"
  "raspberry wine" = "樹莓酒"
  "rattlesnake man venom" = "響尾蛇人毒素"
  "rattlesnake venom" = "響尾蛇毒素"
  "raw adamantine" = "原始精金"
  realgar = "雄黃"
  "red beryl" = "紅柱石"
  "red diamond" = "紅鑽石"
  "red flash opal" = "紅閃歐泊"
  "red grossular" = "紅榴石"
  "red pyrope" = "赤榴石"
  "redroot dye" = "赤根染料"
  "red sand" = "紅沙"
  "red spinel" = "紅尖晶石"
  "red tourmaline" = "紅碧璽"
  "red zircon" = "紅鋯石"
  "reindeer cheese" = "馴鹿乳酪"
  "reindeer's milk" = "馴鹿奶"
  "resin opal" = "脂光歐泊"
  rhodolite = "朱榴石"
  rhyolite = "流紋岩"
  "rice beer" = "稻米啤酒"
  "rice flour" = "稻米麵粉"
  "river spirits" = "河川烈酒"
  rock = "岩石"
  "rock crystal" = "岩石水晶"
  "rock nut" = "石頭堅果"
  "rock nut oil" = "石頭堅果油"
  "rock nut soap" = "石頭堅果皂"
  "rock salt" = "岩鹽"
  "rope reed" = "繩索葦"
  "rose gold" = "玫瑰金"
  "rose quartz" = "薔薇石英"
  "round lime wood" = "圓橘木"
  "rubber wood" = "橡膠樹"
  rubicelle = "橙尖晶石"
  ruby = "紅寶石"
  rutile = "金紅石"
  "rye beer" = "黑麥啤酒"
  "rye flour" = "黑麥麵粉"
  salt = "鹽"
  saltpeter = "硝石"
  sand = "沙"
  "sand pear cider" = "沙梨西打"
  "sand pear wood" = "沙梨木"
  sandstone = "砂岩"
  "sandy clay" = "砂質黏土"
  "sandy clay loam" = "砂質黏壤土"
  "sandy loam" = "砂質壤土"
  sapphire = "藍玉"
  sard = "褐玉髓"
  sardonyx = "纏絲瑪瑙"
  satinspar = "纖維石膏"
  scale = "鱗片"
  schist = "片岩"
  schorl = "黑碧璽"
  seed = "種子"
  selenite = "透明石膏"
  serpentine = "蛇紋石"
  "serpent man venom" = "毒蛇人毒素"
  "sewer brew" = "陰溝佳釀"
  shale = "頁岩"
  "sheep cheese" = "羊奶乳酪"
  "sheep's milk" = "羊奶"
  shell = "殼"
  "shell opal" = "貝殼歐泊"
  "siliceous ooze" = "矽藻軟泥"
  silk = "絲綢"
  silt = "淤泥"
  "silt loam" = "粉質壤土"
  siltstone = "粉砂岩"
  "silty clay" = "粉質粘土"
  "silty clay loam" = "粉質黏壤土"
  silver = "銀"
  sinew = "肌腱"
  "single-grain wheat beer" = "單粒小麥啤"
  "single-grain wheat flour" = "單粒小麥麵粉"
  skin = "皮膚"
  slade = "基岩"
  slate = "板岩"
  "sliver dye" = "裂鉤染料"
  slush = "泥地"
  "smoky quartz" = "煙石英"
  snow = "雪"
  soap = "肥皂"
  "soft wheat beer" = "軟質小麥啤"
  "soft wheat flour" = "軟質小麥麵粉"
  "sorghum beer" = "高粱啤酒"
  "sorghum flour" = "高粱麵粉"
  "spelt beer" = "斯佩爾特麥啤"
  "spelt flour" = "斯佩爾特麥麵粉"
  sphalerite = "閃鋅礦"
  spine = "脊椎"
  spit = "唾液"
  "spleen tissue" = "脾組織"
  "spore tree" = "孢子樹"
  "squid ink" = "魷魚墨汁"
  "squid man ink" = "魷魚人墨汁"
  "star ruby" = "星彩紅寶石"
  "star sapphire" = "星彩藍玉"
  steam = "蒸汽"
  steel = "鋼"
  "sterling silver" = "標準銀"
  stibnite = "輝銻礦"
  "stomach tissue" = "胃組織"
  stoneware = "炻瓷"
  "strawberry wine" = "草莓酒"
  sunshine = "日光酒"
  sunstone = "日長石"
  "swamp whiskey" = "沼澤威士忌"
  sweat = "汗液"
  "sweet potato wine" = "甘薯酒"
  sylvite = "鉀巖"
  talc = "滑石"
  tallow = "脂油"
  tanzanite = "坦桑石"
  "tapir cheese" = "貘乳酪"
  "tapir man cheese" = "貘人乳酪"
  "tapir man's milk" = "貘人奶"
  "tapir's milk" = "貘奶"
  tears = "眼淚"
  "tea wood" = "茶木"
  "teff beer" = "苔麩啤酒"
  "teff flour" = "苔麩麵粉"
  tetrahedrite = "黝銅礦"
  tigereye = "虎眼石"
  "tiger iron" = "虎鐵石"
  tin = "錫"
  "tin glaze" = "錫釉"
  "tomatillo wine" = "燈籠番茄酒"
  "tomato wine" = "番茄酒"
  tooth = "牙齒"
  topaz = "黃玉"
  topazolite = "黃榴石"
  tower-cap = "塔菇"
  "trifle pewter" = "廉白錫"
  tsavorite = "沙弗萊石"
  "tube agate" = "管脈瑪瑙"
  "tuber beer" = "地根啤酒"
  "tunnel tube" = "隧管菌"
  "turnip wine" = "蕪菁酒"
  turquoise = "綠松石"
  "two-grain wheat beer" = "雙粒小麥啤"
  "two-grain wheat flour" = "雙粒小麥麵粉"
  "two-humped camel cheese" = "雙峰駱駝乳酪"
  "two-humped camel man cheese" = "雙峰駱駝人乳酪"
  "two-humped camel man's milk" = "雙峰駱駝人奶"
  "two-humped camel's milk" = "雙峰駱駝奶"
  "unknown boiling creature substance" = "未知沸騰生物質"
  "unknown boiling plant substance" = "未知沸騰植物衍生品"
  "unknown boiling substance" = "未知沸騰物質"
  "unknown creature" = "未知生物"
  "unknown creature substance" = "未知生物質"
  "unknown frozen" = "未知凍結"
  "unknown frozen creature" = "未知生物質"
  "unknown frozen creature substance" = "未知凍結生物質"
  "unknown frozen plant" = "未知凍結植屬"
  "unknown frozen plant substance" = "未知凍結植物衍生品"
  "unknown frozen substance" = "未知凍結物質"
  "unknown plant substance" = "未知植物衍生品"
  "unknown pressed frozen creature substance" = "未知壓實凍結生物質"
  "unknown pressed frozen plant substance" = "未知壓實凍結植物衍生品"
  "unknown slush" = "未知汙水"
  "unknown substance" = "未知物質"
  variscite = "磷鋁石"
  vellum = "皮紙"
  "violet spessartine" = "紫榴石"
  vomit = "嘔吐物"
  "walnut wood" = "胡桃木"
  water = "水"
  "water buffalo cheese" = "水牛奶乳酪"
  "water buffalo's milk" = "水牛奶"
  "wax opal" = "蠟質歐泊"
  "whip vine flour" = "鞭藤麵粉"
  "whip wine" = "長鞭酒"
  "white chalcedony" = "白玉髓"
  "white jade" = "白翡翠"
  "white millet beer" = "白粟啤酒"
  "white millet flour" = "白粟麵粉"
  "white opal" = "白歐泊"
  "white sand" = "白沙"
  willow = "柳樹"
  wine = "葡萄酒"
  "wood opal" = "木歐泊"
  wool = "絨線"
  "yak cheese" = "犛牛乳酪"
  "yak's milk" = "犛牛奶"
  "yellow diamond" = "黃鑽石"
  "yellow grossular" = "緗榴石"
  "yellow jasper" = "黃碧玉"
  "yellow sand" = "黃沙"
  "yellow spessartine" = "橙榴石"
  "yellow zircon" = "黃鋯石"
  zinc = "鋅"
  "rusted metal" = "生鏽金屬"
  "twisting metal" = "扭曲金屬"
  "dark metal" = "黑暗金屬"
  "glowing metal" = "柔和金屬"
  "bright metal" = "明亮金屬"
  "pale metal" = "蒼白金屬"
  "pock-marked metal" = "凹陷金屬"
  "blistered metal" = "鼓泡金屬"
  "ruddy metal" = "紅潤金屬"
  "flickering metal" = "閃爍金屬"
  "faceted metal" = "多面金屬"
  "shining metal" = "發光金屬"
  "flashing metal" = "閃耀金屬"
  "translucent metal" = "透明金屬"
  "frosty metal" = "結霜金屬"
  "slick metal" = "光滑金屬"
  "singing metal" = "振鳴金屬"
  "black metal" = "烏黑金屬"
  "multicolored metal" = "多彩金屬"
  "clear blue metal" = "湛藍金屬"
  "twinkling metal" = "閃亮金屬"
  "crashing metal" = "破碎金屬"
  "blazing metal" = "燃燒金屬"
  "booming metal" = "轟鳴金屬"
  "searing metal" = "灼熱金屬"
  "flowing metal" = "流動金屬"

[[rulesets]]
name = "shared::$0"
optional = true

  [rulesets.rules]
  " paste" = "膏"
  " powder" = "粉末"
  " press cake" = "壓縮餅"
  " slurry" = "漿"
  " paper" = "紙"
