base = "items::bin"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"
"{::items} Bin{$0}" = "{::items}儲物箱{$0}"

[[rulesets]]
name = "$0"
optional = true

  [rulesets.rules]
  " ({::materials::adjective})" = " ({::materials::adjective})"

[[rulesets]]
name = "^0"
optional = true

  [rulesets.rules]
  "{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"

  [rulesets.rules]
  bin = "儲物箱"
  bins = "儲物箱"
