base = "menu::dyer"

[[rulesets]]
[rulesets.rules]
"Dye {kind}" = "染{kind}"
"Dye {kind} a specific color" = "將{kind}染為特定顏色"
"Mix dye" = "混合染料"
"Make dye" = "製作染料"
"Make {::items::dye}" = "製作{::items::dye}"
"Dye {kind} {::color}" = "染{kind}成{::color}"
"Tint {kind} {::color}" = "給{::color}{kind}增色"
"Mix {::color} dye" = "合成{::color}染料"
"Mix {::color} dye {mix$0} {mix$1}" = "合成{::color}染料{mix$0}{mix$1}"
"{tint^0} {::color} {tint$0}" = "{tint^0}{::color}{tint$0}"

[[rulesets]]
name = "kind"

  [rulesets.rules]
  "{::items::thread::main}" = "{::items::thread::main}"
  "{::items::cloth::main}" = "{::items::cloth::main}"
  leather = "皮革"

[[rulesets]]
name = "mix$0"

  [rulesets.rules]
  "using {::color}" = "-使用{::color}"

[[rulesets]]
name = "mix$1"

  [rulesets.rules]
  "and {::color}" = "和{::color}"

[[rulesets]]
name = "tint^0"

  [rulesets.rules]
  "Tint {::color} {kind}" = "將{::color}{kind}增染為"

[[rulesets]]
name = "tint$0"

  [rulesets.rules]
  "using {::items::dye}" = "-使用{::items::dye}"
