base = "menu::kiln"

[[rulesets]]
[rulesets.rules]
"Glaze clay/stone craft" = "為黏土/石頭工藝品上釉"
"Glaze clay/stone jug" = "為黏土/石頭壺上釉"
"Glaze clay/stone statue" = "為黏土/石頭雕像上釉"
"Glaze large clay/stone pot" = "為黏土/石頭大罐上釉"
"Make large clay pot" = "製作大黏土罐"
"Make plaster powder" = "製作石膏粉"
"Make large wooden gem" = "製作大型木製寶石"
"Sew leather image" = "縫綴皮質圖案"
"Sew cloth image" = "縫綴布質圖案"
"Sew silk image" = "縫綴絲質圖案"
"Sew yarn image" = "縫綴紗質圖案"
"Stud with" = "鑲嵌"
"Brew drink from fruit" = "用果實釀酒"
"Brew drink from plant" = "用植物釀酒"
"Make soap from oil" = "用植物油製作肥皂"
"Make soap from tallow" = "用脂油製作肥皂"
"Make quire" = "製作稿紙"
"Make scroll" = "製作卷軸"
"Make wax crafts" = "製作蜂蠟工藝品"
"Bind book" = "裝訂書籍"
"Decorate with horn" = "用角裝飾"
"Decorate with ivory/tooth" = "用長牙/牙齒裝飾"
"Decorate with pearl" = "用珍珠裝飾"
"Make sheet from plant" = "用植物做紙張"
"Milk animal" = "為動物擠奶"
"Process plant to bag" = "用袋子進行甩籽"
"Shear animal" = "為動物剪毛"
"Tan a hide" = "鞣製一張皮革"
"Press honey from honeycomb" = "從蜜脾中壓出蜂蜜"
"Press liquid from fruit" = "從果實中壓出液體"
"Press liquid from paste" = "從漿糊中壓出液體"
"Press plant slurry into paper sheet" = "將植物紙漿壓成紙張"
"Slaughter {::creatures::caste::singular}" = "屠宰{::creatures::caste::singular}"
"Slaughter {::creatures::name::singular}" = "屠宰{::creatures::name::singular}"
"Resting orientation" = "靜置朝向"
"Bolts loaded" = "裝載弩箭數"
"Bolts nearby and available: " = "附近可使用的弩箭數: "
"Bolts nearby but assigned to squads: " = "附近被軍隊佔用的弩箭數: "
"Bolts nearby but assigned to hunters: " = "附近被獵人佔用的弩箭數: "
"Keep loaded but do not stand ready" = "保持裝填狀態但不派人操控"
"Stand ready but do not fire" = "派人操控但不射擊"
"Practice fire (uses many bolts!)" = "進行訓練射擊(將消耗非常多的弩箭!)"
"Practice fire" = "進行訓練射擊"
"* Will also target enemies" = "* 也會向敵人射擊"
"* Place archery targets for better training" = "* 放置箭靶以獲得更好的訓練"
"Fire at enemies" = "向敵人射擊"
"Not in use" = "暫不使用"
