base = "color"

[[rulesets]]
[rulesets.rules]
"{name}" = "{name}"

[[rulesets]]
name = "name"

  [rulesets.rules]
  amber = "琥珀色"
  amethyst = "紫水晶色"
  "apple green" = "蘋果綠"
  aqua = "水色"
  aquamarine = "海藍寶色"
  "ash gray" = "灰白色"
  auburn = "赤褐色"
  azure = "天青色"
  beige = "米色"
  black = "黑色"
  blue = "藍色"
  blue-gray = "藍灰色"
  brass = "黃銅色"
  "bright green" = "亮綠色"
  bronze = "青銅色"
  brown = "棕色"
  buff = "淺黃褐色"
  "burnt sienna" = "焦赭色"
  "burnt umber" = "焦棕色"
  cardinal = "深猩紅色"
  carmine = "胭脂紅"
  cerulean = "蔚藍色"
  charcoal = "木炭灰"
  chartreuse = "查特酒綠"
  chestnut = "栗色"
  chocolate = "巧克力色"
  cinnamon = "肉桂色"
  clear = "透明色"
  cobalt = "鈷藍色"
  copper = "銅色"
  cornflower = "矢車菊藍"
  cream = "奶油色"
  crimson = "緋紅色"
  "crocus purple" = "番紅花紫"
  "dark azure" = "深天青色"
  "dark blue" = "深藍色"
  "dark brown" = "深棕色"
  "dark chestnut" = "深栗色"
  "dark green" = "深綠色"
  "dark indigo" = "深靛藍"
  "dark olive" = "深橄欖色"
  "dark peach" = "深桃色"
  "dark pink" = "深粉色"
  "dark scarlet" = "深猩紅"
  "dark tan" = "深棕褐色"
  "dark violet" = "深紫羅蘭色"
  "deep sea blue" = "深海藍"
  ecru = "米白色"
  eggplant = "茄紫色"
  emerald = "祖母綠色"
  eucalyptus = "桉樹綠"
  "fern green" = "蕨類綠"
  flax = "亞麻色"
  foxglove = "毛地黃紫"
  fuchsia = "紫紅色"
  "glacier blue" = "冰川藍"
  gold = "金色"
  "golden yellow" = "金黃色"
  goldenrod = "金麒麟黃"
  "grass green" = "草綠色"
  gray = "灰色"
  green = "綠色"
  green-yellow = "黃綠色"
  heliotrope = "纈草紫"
  indigo = "靛青色"
  ivory = "象牙色"
  jade = "翡翠色"
  lavender = "薰衣草色"
  "lavender blush" = "薰衣草粉"
  "leaf green" = "葉綠色"
  lemon = "檸檬黃"
  "light blue" = "淺藍色"
  "light brown" = "淺棕色"
  lilac = "丁香紫"
  lime = "酸橙綠"
  mahogany = "桃花心木色"
  maroon = "栗紅色"
  mauve = "淡紫色"
  "mauve taupe" = "灰紫褐色"
  "midnight blue" = "午夜藍"
  "mint green" = "薄荷綠"
  "moss green" = "苔蘚綠"
  ochre = "赭黃色"
  olive = "橄欖色"
  orange = "橙色"
  "orchid pink" = "蘭花粉"
  "pale blue" = "淡藍色"
  "pale brown" = "淡棕色"
  "pale chestnut" = "淡栗色"
  "pale pink" = "淡粉色"
  peach = "桃色"
  pearl = "珍珠色"
  periwinkle = "長春花藍"
  "pine green" = "松樹綠"
  pink = "粉色"
  plum = "梅子色"
  puce = "暗紫褐色"
  pumpkin = "南瓜色"
  purple = "紫色"
  "raspberry pink" = "樹莓粉"
  "raw umber" = "生赭色"
  red = "紅色"
  red-purple = "紅紫色"
  "river blue" = "河畔藍"
  rose = "玫瑰色"
  russet = "赤褐色"
  rust = "鐵鏽色"
  saffron = "藏紅花色"
  sapphire = "寶石藍"
  scarlet = "猩紅色"
  "sea foam" = "海沫綠"
  "sea green" = "海綠色"
  sepia = "烏賊墨色"
  silver = "銀色"
  "sky blue" = "天藍色"
  "slate gray" = "板岩灰"
  "spring green" = "春綠色"
  tan = "棕褐色"
  taupe = "褐色"
  "taupe gray" = "灰褐色"
  "dark taupe" = "深灰褐色"
  "taupe medium" = "中灰褐色"
  "pale taupe" = "淺褐色"
  "purple taupe" = "紫褐色"
  "rose taupe" = "玫瑰褐色"
  "sandy taupe" = "沙褐色"
  teal = "水鴨色"
  turquoise = "青綠色"
  ultramarine = "群青色"
  vermilion = "硃紅色"
  "vibrant green" = "亮翠綠"
  violet = "紫羅蘭色"
  white = "白色"
  "woodland green" = "林地綠"
  yellow = "黃色"
  yellow-green = "黃綠"
  "zesty green" = "鮮檸檬綠"
