base = "health"

[[rulesets]]
[rulesets.rules]
"[C:7:0:1]{bodypart}, {tissue}" = "[C:7:0:1]{bodypart},{tissue}"

[[rulesets]]
name = "tissue"

  [rulesets.rules]
  skin = "皮膚"
  muscle = "肌肉"
  fat = "脂肪"
  "nervous tissue" = "神經組織"
  bone = "骨骼"
  "upper spine" = "上背部脊柱"
  "middle spine" = "背部脊柱"
  "lower spine" = "腰椎"
  skull = "顱骨"

[[rulesets]]
name = "bodypart"

  [rulesets.rules]
  "right upper leg" = "右大腿"
  "right hand" = "右手"
  "left hand" = "左手"
  "left lower arm" = "左前臂"
  "left upper arm" = "左上臂"
  "right upper arm" = "右上臂"
  "right lower arm" = "右前臂"
  head = "頭部"
  neck = "脖子"
  "lower body" = "下半身"
  "upper body" = "上半身"
  "left upper leg" = "左大腿"
  "right lower leg" = "右小腿"
  "left lower leg" = "左小腿"
  "right foot" = "右腳"
  "left foot" = "左腳"
  "right eye" = "右眼"
  "left eye" = "左眼"
  "right ear" = "右耳"
  "left ear" = "左耳"
  nose = "鼻子"
  throat = "喉嚨"
  thumb = "拇指"
  "first finger" = "食指"
  "second finger" = "中指"
  "third finger" = "無名指"
  "fourth finger" = "小指"
  "first toe" = "大腳趾"
  "second toe" = "第二腳趾"
  "third toe" = "第三腳趾"
  "fourth toe" = "第四腳趾"
  "fifth toe" = "第五腳趾"
  mouth = "嘴巴"
  tongue = "舌頭"
  "left cheek" = "左臉頰"
  "right cheek" = "右臉頰"
  "left eyelid" = "左眼瞼"
  "right eyelid" = "右眼瞼"
  "lower lip" = "下唇"
  "upper lip" = "上唇"
  "upper front teeth" = "上門牙"
  "lower front teeth" = "下門牙"
  "lower right back teeth" = "右下臼齒"
  "upper right back teeth" = "右上臼齒"
  "lower left back teeth" = "左下臼齒"
  "upper left back teeth" = "左上臼齒"
