base = "memory"

[[rulesets]]
[rulesets.rules]
"{main}" = "{main}"

[[rulesets]]
name = "main"

  [rulesets.rules]
  "{mind}{memorycolor}dwelling upon{textcolor} {things}{tail}" = "{mind}地{memorycolor}沉思{textcolor}一段{things}的經歷。"
  "{mind}{memorycolor}remembering{textcolor} {things}{tail}" = "{mind}地{memorycolor}回憶起{textcolor}{things}的經歷。"
  "{mind}{memorycolor}reliving{textcolor} {things}{tail}" = "{mind}地{memorycolor}重溫{textcolor}{things}的經歷。"
  "{mind::color}{season} {%number}" = "{mind::color}{%number}年 {season}"

[[rulesets]]
name = "wired"

  [rulesets.rules]
  "{textcolor}{sex}{kind}{mind}{textcolor1} {wired::things}" = "{textcolor}{sex}{kind}{mind}{textcolor1}當{wired::things}"
  "{textcolor}{sex}{kind}{mind}[C:5:0:0] dwelling upon{textcolor1} {wired::things}" = "{textcolor}{sex}{kind}{mind}{textcolor1}{wired::things}"
  "{textcolor}{sex}{kind}{mind}[C:5:0:0] remembering{textcolor1} {wired::things}" = "{textcolor}{sex}{kind}{mind}{textcolor1}{wired::things}"
  "{textcolor}body." = "{textcolor}body."
  "{textcolor}dead body." = "{textcolor}dead body."
  "{textcolor}goblet, cup or mug." = ""
  "{textcolor}{building_name}{tail}" = "{textcolor}{building_name}"
  "{textcolor}{memory::realiton}{tail}" = "{textcolor}和{memory::realiton}"

[[rulesets]]
name = "wired::things"

  [rulesets.rules]
  "seeing {memory::num}{building_own}{building_quility}{building_put}" = "當看到{building_own}{building_quility}{building_put}"
  "near {memory::num}{building_own}{building_quility}{building_put}" = "當靠近{building_own}{building_quility}{building_put}"
  "playing with a" = "在玩了一個"
  "talking with {memory::num}" = "進行交談"

[[rulesets]]
name = "things"

  [rulesets.rules]
  "sleeping in a bedroom like a personal palace." = "在一間個人宮殿般的臥室裡入睡"
  "sleeping in a {memory::poorroom} bedroom" = "在一間{memory::poorroom}臥室入睡"
  "dining in a {memory::poorroom} dining room." = "在一間{memory::poorroom}餐廳就餐"
  "dining in a {memory::poorroom} dining" = "在一間{memory::poorroom}餐廳就餐"
  "dining in a {memory::poorroom}" = "在一間{memory::poorroom}餐廳就餐"
  "sleeping uneasily due to noise." = "因噪音而睡不安穩"
  "being disturbed during sleep by loud noises." = "在睡眠中被巨大的噪音干擾"
  "loud noises made it impossible to sleep." = "在嘈雜的聲音使其無法入睡"
  "sleeping without a proper room." = "在沒有適當房間的情況下入睡"
  "sleeping in the {memory::poorroom}." = "處於{memory::poorroom}睡覺"
  "sleeping on the {memory::poorroom}." = "在{memory::poorroom}之上睡覺"
  "when {memory::poorroom}." = "在{memory::poorroom}時"
  "having a {memory::poorroom} drink." = "享用了一杯{memory::poorroom}飲品"
  "eating a {memory::poorroom}." = "享用了一頓{memory::poorroom}"
  "being forced to eat vermin to survive." = "被迫捕食害蟲以求生後."
  "drinking nasty water." = "飲用難喝的水."
  "drinking the same old booze." = "反覆飲用同一種酒."
  "eating the same old food." = "反覆食用同一種食物."
  "having a drink without using a goblet, cup or mug." = "未使用杯子飲酒"
  "having a drink without using a" = "未使用杯子飲酒"
  "being forced to eat a beloved creature to survive." = "被迫食用心愛的生物以求生"
  "being forced to eat a treasured pet to survive." = "被迫食用珍貴的寵物以求生"
  "seeing {memory::num}{building_own}{building_quility}{building_put} {building_name}" = "看到{building_own}{building_quility}{building_put}{building_name}時"
  "near {memory::num}{building_own}{building_quility}{building_put} {building_name}" = "靠近{building_own}{building_quility}{building_put}{building_name}時"
  "being near to a {::creatures::caste::singular} in a cage." = "靠近籠子裡的{::creatures::caste::singular}"
  "a bath." = "洗完澡"
  "a soapy bath." = "洗完肥皂澡"
  "being near to a waterfall." = "靠近瀑布"
  "retching on a miasma." = "在臭氣中乾嘔"
  "choking on smoke/ underground." = "在地下被煙霧嗆到"
  "choking on dust underground." = "在地下被灰塵嗆到"
  "at the lack of chairs." = "沒有椅子可用"
  "eating at a crowded table." = "在擁擠的桌子旁進食"
  "at the lack of dining tables." = "沒有餐桌可用"
  "being pestered by a {::creatures::caste::singular}." = "被{::creatures::caste::singular}騷擾"
  "being accosted by a {::creatures::caste::singular}." = "被{::creatures::caste::singular}冒犯"
  "being near a {::creatures::caste::singular}." = "靠近{::creatures::caste::singular}"
  "talking with the spouse." = "與配偶交談"
  "talking with mother." = "與母親交談"
  "talking with father." = "與父親交談"
  "talking with a lover." = "與愛人交談"
  "talking with a friend." = "與朋友交談"
  "talking with a sibling." = "與兄弟姐妹交談"
  "talking with a child." = "與孩子交談"
  "talking with somebody." = "與某人交談"
  "talking with an acquaintance." = "與熟人交談"
  "watching a performance." = "觀看錶演"
  "talking to a pillar of society." = "與社會棟梁交談"
  "interacting with a pet." = "與寵物互動"
  "interacting with a animal training partner." = "與動物訓練夥伴互動"
  "visiting with a animal training partner." = "拜訪動物訓練夥伴"
  "visiting with a pet." = "拜訪寵物"
  "discussing {memory::num} {memory::realiton}'s problems." = "討論{memory::realiton}的問題"
  "discussing {memory::num} {memory::realiton}'s" = "討論{memory::realiton}的問題"
  "discussing somebody's problems." = "討論某人的問題"
  "when forced to talk to somebody annoying." = "被迫與令人討厭的人交談時"
  "bringing somebody to rest in bed." = "將某人帶到床上休息"
  "giving somebody food." = "給某人食物"
  "giving somebody water." = "給某人水"
  "making a friend." = "交到新朋友"
  "getting into an argument." = "發生爭吵"
  "forming a grudge." = "產生怨恨"
  "adopting a new pet." = "收養新寵物"
  "at being separated from a loved one." = "與摯愛分離"
  "at being separated from loved ones." = "與摯愛們分離"
  "at work." = "在工作中"
  "producing a masterwork." = "製作傑作"
  "upon mastering {::skills::name}." = "精通{::skills::name}"
  "creating an artifact." = "製作神器"
  "suffering the travesty of art defacement." = "遭受藝術品破壞的悲劇"
  "forming a bond with an animal training partner" = "與動物訓練夥伴建立聯絡"
  "felling a tree" = "砍倒一棵樹"
  "putting a piece on display" = "展示一件物品"
  "to be wearing old clothing" = "穿著破舊的衣服"
  "to be wearing tattered clothing" = "穿著破爛的衣服"
  "to have clothes rot off" = "衣服爛掉"
  "to be uncovered" = "沒有穿褲子"
  "to have no shirt" = "沒有襯衫"
  "to have no shoes" = "沒有鞋"
  "giving birth to *" = "生下*"
  "becoming a parent" = "成為父母"
  "gaining a sibling" = "獲得兄弟姐妹"
  "gaining siblings" = "獲得多個兄弟姐妹"
  "while getting married" = "結婚時"
  "was caught up in a new romance" = "陷入新的戀情"
  "a miscarriage" = "流產之"
  "spouse's miscarriage" = "配偶的流產之"
  "to be elected" = "被選舉"
  "to be re-elected" = "被連任"
  "entering the nobility" = "進入貴族身份"
  "receiving a higher rank of nobility" = "獲得更高爵位的貴族身份"
  "having a {memory::poorroom} tomb after gaining another year" = "獲得另一個生日後擁有{memory::poorroom}陵墓"
  "about not having a tomb after gaining another year" = "關於獲得另一個生日後沒有陵墓"
  "considering the state of demands" = "考慮需求的狀態"
  "to have a mandate deadline met" = "滿足了強令期限"
  "having a mandate deadline missed" = "強令期限錯過"
  "having a mandate ignored" = "強令被忽視"
  "not having enough chests" = "沒有足夠的箱子"
  "not having enough cabinets" = "沒有足夠的櫃子"
  "not having enough weapon racks" = "沒有足夠的武器架"
  "not having enough armor stands" = "沒有足夠的盔甲架"
  "by a lesser's pretentious office arrangements" = "因低等貴族的辦公室安排而感到不滿"
  "by a lesser's pretentious sleeping arrangements" = "因低等貴族的睡眠安排而感到不滿"
  "by a lesser's pretentious dining arrangements" = "因低等貴族的餐飲安排而感到不滿"
  "by a lesser's pretentious burial arrangements" = "因低等貴族的葬禮安排而感到不滿"
  "having to conduct an official meeting in a bedroom" = "不得不在臥室進行官方會議"
  "having to conduct an official meeting in a dining room" = "不得不在餐廳進行官方會議"
  "not having any rooms" = "沒有任何房間"
  "to have his punishment delayed" = "他的懲罰被推遲"
  "to have her punishment delayed" = "她的懲罰被推遲"
  "to have his punishment reduced" = "他的懲罰被減輕"
  "to have her punishment reduced" = "她的懲罰被減輕"
  "punishing somebody with a beating" = "用鞭打懲罰了某人"
  "beating somebody with a hammer" = "用錘子鞭打某人"
  "being released from confinement" = "從監禁中獲釋"
  "that a criminal could not be properly punished" = "罪犯沒有得到適當的懲罰"
  "the delayed punishment of a criminal" = "罪犯的懲罰被推遲"
  "being confined" = "被監禁"
  "considering the scarcity of cages and chains" = "考慮到籠子和鏈條的稀缺性"
  "being beaten" = "被鞭打"
  "being beaten with a hammer" = "被錘子鞭打"
  "being unable to find a hammer" = "找不到錘子"
  "an animal was convicted of a crime" = "動物被判定有罪"
  "a long-dead corpse was convicted of a crime" = "一具久遠的屍體被判定有罪"
  "the bizarre conviction against all reason of the victim of a crime" = "犯罪受害者被不合理地判定有罪"
  "upon receiving justice through a criminal's conviction" = "通過罪犯的定罪獲得正義"
  "when a family member received justice through a criminal's conviction" = "當家庭成員通過罪犯的定罪獲得正義時"
  "being knocked out during a cave-in" = "在塌方中被擊昏"
  "being rescued" = "被救援"
  "being able to rest and recuperate" = "能夠休息和恢復"
  "receiving food" = "接受食物"
  "receiving water" = "接受水"
  "being attacked" = "被攻擊"
  "being attacked by the dead" = "被死者攻擊"
  "being haunted by the dead" = "被死者纏住"
  "being * by a dead {memory::realiton}" = "被已死的{memory::realiton}*"
  "suffering a minor injury" = "遭受輕傷"
  "suffering a major injury" = "遭受重傷"
  "seeing a {::creatures::caste::singular} die." = "看到{::creatures::caste::singular}死亡"
  "seeing a {::creatures::caste::singular}'s dead body." = "看到{::creatures::caste::singular}的屍體"
  "seeing a {::creatures::caste::singular}'s dead" = "看到{::creatures::caste::singular}的屍體"
  "seeing a {::creatures::caste::singular}'s" = "看到{::creatures::caste::singular}的屍體"
  "being tormented in nightmares by a dead {memory::realiton}" = "被已死的{memory::realiton}在噩夢中折磨"
  "being forced to endure the decay of a {memory::realiton}" = "被迫忍受{memory::realiton}的腐爛屍體"
  "being near to a conflict" = "靠近衝突"
  "while in conflict" = "處於衝突中"
  "when joining an existing conflict" = "加入已存在的衝突時"
  "while killing somebody" = "殺死某個矮人時"
  "a sparring session" = "比武練習結束"
  "during long patrol duty" = "長時間巡邏期間"
  "{memory::crime}" = "{memory::crime}"
  "while yelling at somebody in charge" = "對負責人發洩時"
  "while crying on somebody in charge" = "對負責人哭訴時"
  "being unable to find a priest to yell at" = "找不到可以發洩的牧師"
  "being unable to find somebody in charge to yell at" = "找不到可以發洩的負責人"
  "being unable to find a priest to cry on" = "找不到可以哭訴的牧師"
  "being unable to find somebody in charge to cry on" = "找不到可以哭訴的負責人"
  "when caught in {memory::weather}" = "遇到{memory::weather}時"
  "at being out in the sunshine again" = "再次沐浴在陽光下"
  "being nauseated by the sun" = "被陽光弄得反胃"
  "due to inebriation" = "因為醉酒"
  "while performing." = "在表演時"
  "performing." = "表演時"
  "experiencing trauma" = "在經受痛苦經歷"
  "a satisfying acquisition." = "在拿到滿意的東西"
  "putting on {memory::num} {memory::quality} item." = "在穿戴上一件{memory::quality}物品"
  "putting on {memory::num} {memory::quality}" = "在穿戴上一件{memory::quality}物品"
  "playing with a {::items::toy::main}" = "在玩了一個{::items::toy::main}"
  "making a friend" = "交到一個朋友"
  "teaching {memory::skill}" = "教授{memory::skill}"
  "improving {memory::skill}" = "在提高{memory::skill}"
  "learning about {memory::skill}" = "學習{memory::skill}"

[[rulesets]]
name = "memory::num"
optional = true

  [rulesets.rules]
  the = "這個"
  a = "一個"
  an = "一個"

[[rulesets]]
name = "memory::quality"

  [rulesets.rules]
  Well-crafted = "良好做工"
  Finely-crafted = "精美做工"
  Superior = "上等的"
  Exceptional = "卓越的"
  Masterful = "大師的"
  Artifact = "神器"

[[rulesets]]
name = "memory::skill"

  [rulesets.rules]
  Mining = "採礦"
  Woodcutting = "伐木"
  Carpentry = "木工"
  Engraving = "雕刻"
  Masonry = "石工"
  "Animal Training" = "馴獸"
  "Animal Caretaking" = "動物護理"
  "Fish Dissection" = "剖魚"
  "Animal Dissection" = "動物解剖"
  "Fish Cleaning" = "洗魚"
  Butchery = "屠宰"
  Trapping = "誘捕"
  Tanning = "製革"
  Weaving = "編織"
  Brewing = "釀造"
  Tailoring = "裁縫"
  Milling = "碾磨"
  Threshing = "脫粒"
  Cheesemaking = "制酪"
  Milking = "擠奶"
  Cooking = "烹飪"
  Planting = "種植"
  Herbalism = "草藥學"
  Fishing = "捕魚"
  "Furnace Operation" = "火爐操作"
  "Strand Extraction" = "縷絲提取"
  Weaponsmithing = "武器鍛造"
  Armorsmithing = "盔甲鍛造"
  Blacksmithing = "鍛造"
  "Gem Cutting" = "寶石切割"
  "Gem Setting" = "寶石鑲嵌"
  Woodcrafting = "木藝"
  Stonecrafting = "石藝"
  Metalcrafting = "金屬工藝"
  Glassmaking = "玻璃製作"
  Leatherworking = "皮革加工"
  "Bone Carving" = "骨雕"
  Knife = "小刀使用"
  Crossbow = "弩術"
  Shield = "盾牌使用"
  Armor = "盔甲使用"
  "Siege Engineering" = "攻城器工程"
  "Siege Operation" = "攻城器操作"
  Bowyery = "制弓"
  Lashing = "鞭術"
  Archery = "射術"
  Blowgun = "吹管術"
  Throwing = "投擲"
  Mechanics = "機械學"
  machinery = "機械"
  Druidism = "德魯伊教"
  Ambushing = "伏擊"
  "Wound Dressing" = "裹傷"
  Diagnosis = "診斷"
  Surgery = "外科手術"
  "Bone Setting" = "骨科"
  Suturing = "縫合"
  Crutch-walking = "拄拐行走"
  "Wood Burning" = "燒炭"
  "Lye Making" = "制鹼液"
  "Soap Making" = "制皂"
  "Potash Making" = "制草鹼"
  Dyeing = "染色"
  "Pump Operation" = "泵機操作"
  Swimming = "游泳"
  Persuasion = "說服"
  Negotiation = "交涉"
  "Judging Intent" = "意圖判斷"
  Appraisal = "估價"
  Organization = "組織能力"
  "Record Keeping" = "記錄"
  Lying = "說謊"
  Intimidation = "恐嚇"
  Conversation = "交談"
  Comedy = "喜劇表演"
  Flattery = "奉承"
  Consolation = "安慰"
  Pacification = "調解"
  Tracking = "追蹤"
  Studying = "學習"
  Concentration = "專注"
  Discipline = "遵守紀律"
  Observation = "觀察"
  Wordsmithing = "文字創作"
  Writing = "寫作"
  Poetry = "作詩"
  Reading = "閱讀"
  Speaking = "演講"
  Coordination = "協調"
  Balance = "平衡"
  Leadership = "領導"
  Teaching = "教學"
  Fighting = "戰鬥"
  Wrestling = "摔跤"
  Biting = "撕咬"
  Striking = "搏擊"
  Kicking = "踢擊"
  Dodging = "躲閃"
  "Misc. Object" = "雜物使用"
  Knapping = "碎石"
  Tactics = "戰術"
  Shearing = "剪毛"
  Spinning = "紡紗"
  Pottery = "製陶"
  Glazing = "上釉"
  Pressing = "壓榨"
  Beekeeping = "養蜂"
  "Wax Working" = "蠟工"
  Climbing = "攀爬"
  Gelding = "閹割"
  Dancing = "舞蹈"
  Musicianship = "音樂演奏"
  Singing = "歌唱"
  Keyboard = "鍵盤演奏"
  "Stringed Instrument" = "絃樂演奏"
  "Wind Instrument" = "管樂演奏"
  Percussion = "打擊樂演奏"
  "Critical Thinking" = "批判性思維"
  Logic = "邏輯學"
  Mathematics = "數學"
  Astronomy = "天文學"
  Chemistry = "化學"
  Geography = "地理學"
  "Optics Engineering" = "光學工程"
  "Fluid Engineering" = "流體工程"
  Papermaking = "造紙"
  Bookbinding = "書籍裝訂"
  Scheming = "陰謀策劃"
  Riding = "騎術"
  Stonecutting = "切石"
  "Stone Carving" = "石雕"
  Axe = "斧術"
  Sword = "劍術"
  Mace = "頁錘術"
  Hammer = "戰錘術"
  Spear = "矛術"
  Marksmanship = "射擊術"
  Pike = "長槍術"
  bow = "弓術"
  Furnace = "火爐操作"

[[rulesets]]
name = "building_quility"

  [rulesets.rules]
  " very fine" = "非常精美的"
  " splendid" = "極佳的"
  " wonderful" = "奇妙的"
  " completely sublime" = "完全卓越的"
  " fine" = "非常精美的"

[[rulesets]]
name = "building_put"
optional = true

  [rulesets.rules]
  " tastefully arranged" = "精心佈置的"

[[rulesets]]
name = "building_own"
optional = true

  [rulesets.rules]
  " own" = "自己的"

[[rulesets]]
name = "building_name"

  [rulesets.rules]
  "{::items::main}" = "{::items::main}"
  seat = "座位"
  "{::construction_menu}" = "{::construction_menu}"

[[rulesets]]
name = "memory::poorroom"

  [rulesets.rules]
  "horribly substandard" = "嚴重不合標準的"
  horrible = "可怕的"
  awful = "糟糕的"
  "very poor" = "非常差的"
  poor = "差的"
  legendary = "傳奇的"
  fantastic = "奇妙的"
  great = "絕妙的"
  "very good" = "非常好的"
  good = "好的"
  mud = "淤泥"
  dirt = "泥土"
  grass = "草"
  rocks = "岩石"
  ice = "冰"
  "a rough cave floor" = "粗糙的洞穴樓板"
  floor = "樓板"
  "a pile of driftwood" = "一堆浮木"
  drowsy = "昏昏欲睡"
  "utterly sleep-deprived" = "全然睡眠不足"
  "pretty decent" = "相當不錯的"
  fine = "精美的"
  wonderful = "奇妙的"
  "truly decadent" = "真正的奢華的"
  "pretty decent meal" = "相當不錯的飯菜"
  "fine dish" = "精美的菜餚"
  "wonderful dish" = "奇妙的菜餚"
  "truly decadent dish" = "真正的奢華菜餚"
  "legendary meal" = "傳奇的飯菜"
  thirsty = "口渴"
  hungry = "飢餓"
  dehydrated = "脫水"
  starving = "餓死"

[[rulesets]]
name = "memory::realiton"

  [rulesets.rules]
  "animal training partner." = "動物訓練夥伴"
  "pet." = "寵物"
  spouse = "配偶"
  mother = "母親"
  father = "父親"
  lover = "愛人"
  friend = "朋友"
  acquaintance = "熟人"
  sibling = "兄弟姐妹"
  child = "孩子"
  somebody = "某人"
  "somebody annoying" = "令人討厭的人"
  "still annoying acquaintance" = "仍令人討厭的熟人"
  "and still annoying acquaintance" = "且仍令人討厭的熟人"

[[rulesets]]
name = "memory::crime"

  [rulesets.rules]
  "throwing something" = "扔東西"
  "toppling something over" = "推倒東西"
  "smashing up a building" = "破壞建築"
  "starting a fist fight" = "開始打架"

[[rulesets]]
name = "memory::weather"

  [rulesets.rules]
  "the rain" = "下雨"
  "a snow storm" = "下雪"
  "freakish weather" = "異常天氣"

[[rulesets]]
name = "dead"

  [rulesets.rules]
  "human's dead body." = "人類屍體"
  "goblin's dead body." = "哥布林屍體"
  "human's dead" = "人類屍體"
  "goblin's dead" = "哥布林屍體"

[[rulesets]]
name = "sex"

  [rulesets.rules]
  He = "他"
  She = "她"

[[rulesets]]
name = "mind"

  [rulesets.rules]
  "{mind::color}{mind::text}" = "{mind::color}{mind::text}"

[[rulesets]]
name = "mind::color"
optional = true

  [rulesets.rules]
  "[C:2:0:1]" = "[C:2:0:1]"
  "[C:2:0:0]" = "[C:2:0:0]"
  "[C:4:0:1]" = "[C:4:0:1]"
  "[C:4:0:0]" = "[C:4:0:0]"
  "[C:7:0:1]" = "[C:7:0:1]"
  "[C:7:0:0]" = "[C:7:0:0]"
  "[C:3:0:1]" = "[C:3:0:1]"
  "[C:3:0:0]" = "[C:3:0:0]"
  "[C:1:0:1]" = "[C:1:0:1]"
  "[C:6:0:1]" = "[C:6:0:1]"
  "[C:6:0:0]" = "[C:6:0:0]"
  "[C:5:0:1]" = "[C:5:0:1]"
  "[C:5:0:0]" = "[C:5:0:0]"

[[rulesets]]
name = "mind::text"

  [rulesets.rules]
  Adoration = "崇拜"
  Admiration = "欽佩"
  Affection = "喜愛"
  Aroused = "興奮"
  Caring = "關心"
  Empathy = "同理"
  Enraptured = "陶醉"
  Fondness = "喜歡"
  Gratitude = "感激"
  Lustful = "難以自持"
  Love = "愛意"
  Passionate = "熱情"
  Pleasure = "愉悅"
  Proud = "自豪"
  Repentant = "懺悔"
  Sympathy = "同情"
  Tenderness = "溫柔"
  Amused = "好笑"
  Blissful = "極度幸福"
  Content = "滿足"
  Delighted = "欣喜"
  Elated = "興高采烈"
  Enjoyment = "愉快"
  Euphoric = "欣快"
  Expectant = "期待"
  Free = "自由"
  Gaiety = "歡快"
  Happy = "開心"
  Hope = "有希望"
  Jovial = "開朗"
  Joy = "喜悅"
  Relieved = "放心"
  Satisfied = "滿意"
  Triumph = "得意"
  Optimistic = "樂觀"
  Astonished = "驚訝"
  Awe = "敬畏"
  Excited = "興奮"
  Eager = "渴望"
  Exhilarated = "振奮"
  Interested = "有趣"
  Wonder = "驚歎"
  Accepting = "接納"
  Ambivalent = "矛盾"
  "Grim Satisfaction" = "冷酷的滿足"
  Suspicious = "懷疑"
  Aggravated = "惱火"
  Agitated = "焦躁"
  Annoyed = "煩惱"
  Anxious = "焦慮"
  Bitter = "苦澀"
  Bored = "無聊"
  Confused = "困惑"
  Contemptuous = "輕蔑"
  Dejected = "沮喪"
  Disappointed = "失望"
  Disillusioned = "幻滅"
  Dislike = "不喜歡"
  Embarrassed = "尷尬"
  Exasperated = "惱怒"
  Frustrated = "挫敗"
  Gloomy = "陰鬱"
  Glum = "鬱悶"
  Grouchy = "脾氣暴躁"
  Guilty = "內疚"
  Indignant = "憤慨"
  Insulted = "受辱"
  Irritated = "惱火"
  Isolated = "被孤立"
  Lonely = "孤獨"
  Regretful = "後悔"
  Resentful = "怨恨"
  Restless = "坐立不安"
  Self-Pity = "自憐"
  Uneasy = "不安"
  Worried = "擔心"
  Anguish = "痛苦萬分"
  Ashamed = "羞愧"
  Despair = "絕望"
  Disgusted = "厭惡"
  Distressed = "痛苦"
  Empty = "空虛"
  "Existential Crisis" = "陷入存在危機"
  Frightened = "驚恐"
  Grieved = "悲痛"
  Hopeless = "毫無希望"
  Humiliated = "屈辱"
  Mortified = "羞愧難當"
  Panicked = "驚慌失措"
  Sad = "悲傷"
  Shaken = "震驚不已"
  Shocked = "震驚"
  Alarmed = "驚慌"
  Afraid = "害怕"
  Angry = "憤怒"
  Ferocity = "兇狠"
  Horrified = "驚駭"
  Loathing = "憎惡"
  Outraged = "暴怒不已"
  Terrified = "極度恐懼"
  Vengeful = "復仇心切"

[[rulesets]]
name = "kind"

  [rulesets.rules]
  " is" = "感到"
  " was" = "感到"
  " didn't feel" = ""
  " doesn't feel" = ""
  " feels" = "感到"
  " felt" = "感到"

[[rulesets]]
name = "textcolor"

  [rulesets.rules]
  "[C:7:0:1]" = "[C:7:0:1]"
  "[C:7:0:0]" = "[C:7:0:0]"

[[rulesets]]
name = "textcolor1"
optional = true

  [rulesets.rules]
  "[C:7:0:1]" = "[C:7:0:1]"
  "[C:7:0:0]" = "[C:7:0:0]"

[[rulesets]]
name = "memorycolor"

  [rulesets.rules]
  "[C:5:0:1] " = "[C:5:0:1]"
  "[C:5:0:0] " = "[C:5:0:0]"

[[rulesets]]
name = "tail"
optional = true

  [rulesets.rules]
  "." = "."

[[rulesets]]
name = "season"

  [rulesets.rules]
  spring = "春"
  summer = "夏"
  autumn = "秋"
  winter = "冬"
