base = "require"

[[rulesets]]
[rulesets.rules]
"[Requires {main}]" = "[需要{main}]"

[[rulesets]]
name = "main"

  [rulesets.rules]
  "Unrotten fermentable leaf or fruit" = "未腐爛的可發酵的葉或果實"
  "Unrotten fermentable plants" = "未腐爛的可發酵植物"
  "Honey-containing item" = "裝有蜂蜜的物品"
  Potash = "草鹼"
  "Clay boulders" = "黏土"
  "Empty bag" = "空袋子"
  "Empty unimproved glazable item" = "未上釉的可上釉的工藝品"
  "Empty unimproved glazable jug" = "未上釉的可上釉的空壺"
  "Empty unimproved glazable statue" = "未上釉的可上釉的雕像"
  "Empty unimproved glazable large pot" = "未上釉的可上釉的空大罐"
  "Gypsum boulders" = "石膏巖塊"
  "Calcite/limestone/chalk/marble boulders" = "方解石/石灰岩/白堊巖/大理石巖塊"
  Window = "窗"
  "Plant logs" = "窗"
  "Oil-containing item" = "裝有植物油的物品"
  "Unrotten tallow fatty glob" = "未腐爛的脂油球團"
  "Lye-containing item" = "裝有鹼液的物品"
  "Scroll rollers" = "捲筒"
  "Wax glob" = "蜂蠟軟團"
  "Collected thread" = "已收集的細線"
  Sheet = "紙張"
  "Book binding" = "書皮"
  "Unrotten bone body part" = "未腐爛的骨頭組織"
  Logs = "原木"
  "Non-economic hard stone boulders" = "非經濟硬質石塊"
  "Unrotten shell body part" = "未腐爛的殼組織"
  "Collected plant thread" = "已收集的植物細線"
  "Unrotten paper-making plants" = "未腐爛的可造紙的植物"
  "Milk of lime-containing item" = "裝有石灰乳的物品"
  "Unrotten tannable body part" = "未腐爛的可鞣製的身體組織"
  "Empty bucket" = "空提桶"
  "Quicklime-containing item" = "裝有生石灰的物品"
  "Non-pressed honey-bearing honeycomb" = "未壓制的含有蜂蜜的蜜脾"
  "Unrotten non-pressed oil-bearing leaf or fruit" = "未腐爛的含油果實/葉子"
  "Non-pressed oil-bearing glob" = "未壓制的含油軟團"
  "Non-pressed paper-slurry glob" = "未壓制的紙漿"
  "Liquid container" = "液體容器"
  "Tanned hide" = "鞣製的生皮"
  "Unrotten paper-slurryable plants" = "未腐爛的可製紙漿植物"
  "Unrotten oil-bearing seeds" = "未腐爛的含油種子"
  "Sand-containing item" = "裝有沙子的物品"
  "Written-on quire" = "被書寫的手稿"
  "Flux boulders" = "熔劑石"
  fuel = "燃料"
  ore = "礦石"
  "ore, fuel" = "礦石,燃料"
  "Bituminous coal" = "煙煤"
  Lignite = "褐煤"
  "Adamantine strands" = "精金縷"
  "Zinc-bearing boulders" = "含鋅礦石"
  "Tin-bearing boulders" = "含錫礦石"
  "Copper-bearing boulders" = "含銅礦石"
  "Silver-bearing boulders" = "含銀礦石"
  "Gold-bearing boulders" = "含金礦石"
  "{::materials} ore" = "{::materials}礦石"
  "{::items::bar}" = "{::items::bar}"
  "Refined coal" = "精煉煤"
