base = "skills"

[[rulesets]]
[rulesets.rules]
"{level} {name}" = "{level}{name}"

[[rulesets]]
name = "level"

  [rulesets.rules]
  Dabbling = "涉足的"
  Novice = "新手的"
  Adequate = "勉強的"
  Competent = "合格的"
  Skilled = "熟練的"
  Proficient = "精通的"
  Talented = "聰穎的"
  Adept = "拿手的"
  Expert = "專業的"
  Professional = "內行的"
  Accomplished = "嫻熟的"
  Great = "偉大的"
  Master = "大師級的"
  "High Master" = "宗師級的"
  "Grand Master" = "泰斗級的"
  Legendary = "傳奇的"

[[rulesets]]
name = "name"

  [rulesets.rules]
  Miner = "礦工"
  Woodcutter = "樵夫"
  Carpenter = "木匠"
  Engraver = "雕刻師"
  Mason = "石匠"
  "Animal Trainer" = "馴獸師"
  "Animal Caretaker" = "動物護理員"
  "Fish Dissector" = "剖魚工"
  "Animal Dissector" = "動物解剖員"
  "Fish Cleaner" = "洗魚工"
  Butcher = "屠夫"
  Trapper = "誘捕者"
  Tanner = "製革工"
  Weaver = "織工"
  Brewer = "釀造師"
  Clothier = "裁縫"
  Miller = "碾磨工"
  Thresher = "脫粒工"
  Cheesemaker = "制酪工"
  Milker = "擠奶工"
  Cook = "廚師"
  Planter = "播種者"
  Herbalist = "草藥師"
  Fisherman = "漁夫"
  "Furnace Operator" = "火爐操作員"
  "Strand Extractor" = "縷絲提取師"
  Weaponsmith = "武器匠"
  Armorsmith = "盔甲匠"
  Blacksmith = "鍛造師"
  "Gem Cutter" = "寶石切割師"
  "Gem Setter" = "寶石鑲嵌師"
  Woodcrafter = "木藝師"
  "Stone Crafter" = "石藝師"
  "Metal Crafter" = "金屬工匠"
  Glassmaker = "玻璃匠"
  Leatherworker = "皮匠"
  "Bone Carver" = "骨雕師"
  Axeman = "斧手"
  Swordsman = "劍士"
  "Knife User" = "小刀使用者"
  Maceman = "頁錘手"
  Hammerman = "戰錘手"
  Spearman = "矛手"
  Crossbowman = "弩手"
  "Shield User" = "盾牌使用者"
  "Armor User" = "盔甲使用者"
  "Siege Engineer" = "攻城器技師"
  "Siege Operator" = "攻城器操作員"
  Bowyer = "弩匠"
  Pikeman = "長槍手"
  Lasher = "鞭撻者"
  Bowman = "弓手"
  Blowgunner = "吹管手"
  Thrower = "投擲者"
  Mechanic = "機械師"
  Druid = "德魯伊"
  Ambusher = "伏擊者"
  "Wound Dresser" = "裹傷師"
  Diagnostician = "診斷醫師"
  Surgeon = "外科醫師"
  "Bone Doctor" = "骨科醫師"
  Suturer = "縫合師"
  Crutch-walker = "拄拐行者"
  "Wood Burner" = "燒炭工"
  "Lye Maker" = "制鹼液者"
  Soaper = "皂工"
  "Potash Maker" = "制草鹼者"
  Dyer = "染工"
  "Pump Operator" = "泵機操作員"
  Swimmer = "游泳者"
  Persuader = "說服者"
  Negotiator = "交涉者"
  "Judge of Intent" = "意圖判斷"
  Appraiser = "估價員"
  Organizer = "組織者"
  "Record Keeper" = "記錄員"
  Liar = "說謊者"
  Intimidator = "恐嚇者"
  Conversationalist = "健談者"
  Comedian = "趣者"
  Flatterer = "奉承者"
  Consoler = "慰藉者"
  Pacifier = "調解者"
  Tracker = "追蹤者"
  Student = "學生"
  Concentration = "專注"
  Discipline = "遵守紀律"
  Observer = "觀察者"
  Wordsmith = "文學家"
  Writer = "作者"
  Poet = "詩人"
  Reader = "閱讀者"
  Speaker = "講述者"
  Coordination = "協調"
  Balance = "平衡"
  Leader = "領導者"
  Teacher = "教師"
  Fighter = "戰士"
  Archer = "射手"
  Wrestler = "摔跤手"
  Biter = "撕咬者"
  Striker = "搏擊者"
  Kicker = "踢擊者"
  Dodger = "躲閃者"
  "Misc. Object User" = "雜物使用者"
  Knapper = "碎石者"
  Tactician = "戰術家"
  Shearer = "剪毛工"
  Spinner = "紡紗工"
  Potter = "陶藝師"
  Glazer = "釉工"
  Presser = "壓榨工"
  Beekeeper = "養蜂人"
  "Wax Worker" = "蠟工"
  Climber = "攀爬者"
  Gelder = "騸匠"
  Dancer = "舞蹈家"
  Musician = "音樂家"
  Singer = "歌唱家"
  Keyboardist = "鍵盤樂師"
  "Stringed Instrumentalist" = "絃樂師"
  "Wind Instrumentalist" = "管樂師"
  Percussionist = "打擊樂師"
  "Critical Thinker" = "批判思考者"
  Logician = "邏輯學家"
  Mathematician = "數學家"
  Astronomer = "天文學家"
  Chemist = "化學家"
  Geographer = "地理學家"
  "Optics Engineer" = "光學工程師"
  "Fluid Engineer" = "流體工程師"
  Papermaker = "造紙工"
  Bookbinder = "書籍裝訂員"
  Schemer = "陰謀家"
  Rider = "騎手"
  Stonecutter = "切石師"
  "Stone Carver" = "石雕師"
  fisherdwarf = "矮人漁夫"
  axedwarf = "矮人斧手"
  swordsdwarf = "矮人劍士"
  macedwarf = "矮人頁錘手"
  hammerdwarf = "矮人戰錘手"
  speardwarf = "矮人矛手"
  marksdwarf = "矮人弩手"
  pikedwarf = "矮人長槍手"
  bowdwarf = "矮人弓手"
