base = "positions::mountain"

[[rulesets]]
name = "singular"

  [rulesets.rules]
  monarch = "君主"
  general = "將軍"
  lieutenant = "中尉"
  captain = "隊長"
  "militia commander" = "軍事指揮官"
  "militia captain" = "軍事隊長"
  sheriff = "治安官"
  "captain of the guard" = "衛隊統領"
  "expedition leader" = "遠征領袖"
  mayor = "市長"
  manager = "經理人"
  "chief medical dwarf" = "首席矮人醫師"
  broker = "交易員"
  bookkeeper = "簿記員"
  "outpost liaison" = "前哨聯絡員"
  diplomat = "外交官"
  duke = "公爵"
  count = "伯爵"
  baron = "男爵"
  champion = "冠軍"
  hammerer = "錘刑官"
  "dungeon master" = "地牢主管"
  administrator = "管理員"
  messenger = "信使"

[[rulesets]]
name = "plural"

  [rulesets.rules]
  monarchs = "君主"
  generals = "將軍"
  lieutenants = "中尉"
  captains = "隊長"
  "militia commanders" = "軍事指揮官"
  "militia captains" = "軍事隊長"
  sheriffs = "治安官"
  "captains of the guard" = "衛隊統領"
  "expedition leaders" = "遠征領袖"
  mayors = "市長"
  managers = "經理人"
  "chief medical dwarves" = "首席矮人醫師"
  brokers = "交易員"
  bookkeepers = "簿記員"
  "outpost liaisons" = "前哨聯絡員"
  diplomats = "外交官"
  dukes = "公爵"
  counts = "伯爵"
  barons = "男爵"
  champions = "冠軍"
  hammerers = "錘刑官"
  "dungeon masters" = "地牢主管"
  administrators = "管理員"
  messengers = "信使"
