--@module = true

local helpers = reqscript('df-local-zh-core/helpers')

-- collect DF version
OS = dfhack.getOSType()
DF_PLATFORM = dfhack.getDFVersion():split(' ', true)[3]:lower()
DF_VERSION = dfhack.getCompiledDFVersion()

-- get a native library function
local lib_file = (OS == "windows") and "df_local_zh_core.dll" or "libdf_local_zh_core.so"
local lib_path = helpers.MOD_SOURCE_PATH .. "libs/" .. lib_file
function lib_function(symbol)
  return assert(package.loadlib(lib_path, symbol))
end

-- load native library functions
setup = lib_function("setup")
init = lib_function("init")
enable = lib_function("enable")
disable = lib_function("disable")
toggle = lib_function("toggle")
set_view_screen = lib_function("set_view_screen")
add_memory_region = lib_function("add_memory_region")
add_memory_search = lib_function("add_memory_search")
add_font = lib_function("add_font")
load_title_logo = lib_function("load_title_logo")
load_simple_dict = lib_function("load_simple_dict")
load_translation_rulesets = lib_function("load_translation_rulesets")
set_lang_tag = lib_function("set_lang_tag")
reset = lib_function("reset")
sync_translate = lib_function("sync_translate")
async_translate = lib_function("async_translate")
is_enabled = lib_function("is_enabled")
interception_bypass_enable = lib_function("interception_bypass_enable")
interception_bypass_disable = lib_function("interception_bypass_disable")
dfhack_addstr_flag = lib_function("dfhack_addstr_flag")
cache_lookup = lib_function('cache_lookup')
localize_text = lib_function('localize_text')
color_persistence_set = lib_function('color_persistence_set')
broker_timeout_set = lib_function('broker_timeout_set')
core_trace_enable = lib_function('core_trace_enable')
core_trace_read = lib_function('core_trace_read')
core_validate_hooks = lib_function('core_validate_hooks')
core_cache_metrics = lib_function('core_cache_metrics')
search_set_query = lib_function('search_set_query')
search_clear = lib_function('search_clear')
search_matches = lib_function('search_matches')
search_metrics = lib_function('search_metrics')
search_cache_metrics = lib_function('search_cache_metrics')
search_pinyin_enable = lib_function('search_pinyin_enable')
search_load_normalization = lib_function('search_load_normalization')
search_input_focus = lib_function('search_input_focus')
search_input_drain = lib_function('search_input_drain')
search_push_text = lib_function('search_push_text')
search_push_key = lib_function('search_push_key')
search_widget_notify = lib_function('search_widget_notify')
search_columns = lib_function('search_columns')
search_push_composition = lib_function('search_push_composition')
native_set_world = lib_function('native_set_world')
native_prewarm_request = lib_function('native_prewarm_request')
native_prewarm_status = lib_function('native_prewarm_status')
official_library_status = package.loadlib(lib_path,'official_library_status')
official_library_lookup = package.loadlib(lib_path,'official_library_lookup')
native_display_rows_set = lib_function('native_display_rows_set')
native_display_rows_status = lib_function('native_display_rows_status')
cloud_enable = lib_function('cloud_enable')
cloud_disable = lib_function('cloud_disable')
cloud_get_status = lib_function('cloud_get_status')
cloud_set_endpoint = lib_function('cloud_set_endpoint')
developer_mode_enable = lib_function('developer_mode_enable')
developer_mode_disable = lib_function('developer_mode_disable')
developer_mode_get_status = lib_function('developer_mode_get_status')
runtime_worker_threads_get = lib_function('runtime_worker_threads_get')
runtime_worker_threads_set = lib_function('runtime_worker_threads_set')
-- Optional during a live Lua update; the attached older DLL stays loaded.
translation_concurrency_get = package.loadlib(lib_path,'translation_concurrency_get')
translation_concurrency_set = package.loadlib(lib_path,'translation_concurrency_set')
persistent_cache_refresh = lib_function('persistent_cache_refresh')
persistent_cache_enable = lib_function('persistent_cache_enable')
persistent_cache_disable = lib_function('persistent_cache_disable')
persistent_cache_get_status = lib_function('persistent_cache_get_status')
persistent_cache_clear = lib_function('persistent_cache_clear')

-- setup global variable or field offset
function setup_globals(stmt)
  local symbol = ("set_%s"):format(stmt:gsub('%.', '_'))
  local setter_function = lib_function(symbol)
  local field = helpers.eval(string.gsub("df.global." .. stmt, "%.([^.]*)$", ":_field('%1')"))
  local _, addr = df.sizeof(field)
  setter_function(addr)
end
