base = "plants::name"

[[rulesets]]
[rulesets.rules]
"{singular}" = "{singular}"
"{plural}" = "{plural}"

[[rulesets]]
name = "singular"

  [rulesets.rules]
  "abaca tree" = "蕉麻樹"
  acacia = "刺槐"
  alder = "榿樹"
  alfalfa = "苜蓿"
  "almond tree" = "扁桃樹"
  "apple tree" = "蘋果樹"
  "apricot tree" = "杏樹"
  "arrow bamboo" = "箭竹"
  artichoke = "洋薊"
  ash = "白蠟樹"
  asparagus = "蘆筍"
  "avocado tree" = "鱷梨樹"
  "baby toes succulent" = "幼趾多肉"
  "bambara groundnut plant" = "班巴拉花生植株"
  "banana tree" = "香蕉樹"
  barley = "大麥"
  "bayberry tree" = "楊梅樹"
  "beet plant" = "甜菜植株"
  bentgrass = "糠穗草"
  "bilberry bush" = "越橘灌木"
  birch = "樺樹"
  "bitter melon vine" = "苦瓜藤"
  "bitter orange tree" = "苦橙樹"
  "bitter vetch" = "苦野豌豆"
  "blackberry bush" = "黑莓灌木"
  black-cap = "黑菇"
  "blade weed" = "刀刃草"
  "bloated tuber" = "膨地根"
  "blood amaranth" = "血莧"
  "blood thorn" = "血荊棘"
  "blueberry bush" = "藍莓灌木"
  "blue sedge" = "藍苔莎"
  "broad bean plant" = "蠶豆植株"
  "bubble bulb" = "泡泡球莖"
  buckwheat = "蕎麥"
  cabbage = "捲心菜"
  "cacao tree" = "可可樹"
  candlenut = "石栗"
  "caper bush" = "刺山柑灌木"
  "carambola tree" = "楊桃樹"
  carpetgrass = "地毯草"
  "cashew tree" = "腰果樹"
  cassava = "木薯"
  cattail = "貓尾草"
  "cave moss" = "洞穴苔蘚"
  "cave wheat" = "洞穴小麥"
  cedar = "雪松"
  celery = "芹菜"
  "cherry tree" = "櫻桃樹"
  chestnut = "板栗樹"
  "chickpea plant" = "鷹嘴豆植株"
  chicory = "菊苣"
  "citron tree" = "香櫞樹"
  cloudberry = "雲莓"
  "coconut palm" = "椰棕櫚"
  "coffee tree" = "咖啡樹"
  "common reed" = "蘆葦"
  cottongrass = "棉草"
  "cotton plant" = "棉花植株"
  "cowpea plant" = "豇豆植株"
  "cranberry vine" = "蔓越莓藤"
  "cucumber vine" = "黃瓜藤"
  "custard-apple tree" = "番荔枝樹"
  dallisgrass = "雀稗草"
  "date palm" = "棗棕櫚"
  "desert lime tree" = "漠橘樹"
  "dimple cup" = "窩杯菇"
  "dog's tooth grass" = "狗牙草"
  "downy grass" = "羽絨草"
  "dropseed grass" = "落籽草"
  "durian tree" = "榴槤樹"
  eggplant = "茄子"
  "elephant-head amaranth" = "象頭莧"
  "feather tree" = "羽毛樹"
  "fescue grass" = "細葉草"
  "field sedge" = "田野莎草"
  "finger lime tree" = "指橘樹"
  "finger millet plant" = "爪粟植株"
  "fisher berry" = "漁夫漿果"
  "flax plant" = "亞麻植株"
  "floor fungus" = "地真菌"
  "fonio plant" = "非尼奧米植株"
  "foxtail millet plant" = "狐尾粟植株"
  fungiwood = "真菌木"
  "garden cress" = "水芹"
  "garlic plant" = "大蒜植株"
  "ginkgo tree" = "銀杏樹"
  glumprong = "紫影樹"
  goblin-cap = "妖精菇"
  "golden bamboo" = "金竹"
  grama = "格蘭馬草"
  "grape vine" = "葡萄藤"
  "guava tree" = "番石榴樹"
  "hair grass" = "發草"
  "hard wheat" = "硬質小麥"
  "hazel tree" = "榛樹"
  "hedge bamboo" = "籬笆竹"
  "hemp plant" = "大麻植株"
  "hide root" = "匿莖草"
  highwood = "極樹"
  "horned melon vine" = "刺角瓜藤"
  "jute plant" = "黃麻植株"
  kaniwa = "彩藜"
  kapok = "木棉樹"
  "kenaf plant" = "洋麻植株"
  knotgrass = "繩結草"
  "kobold bulb" = "犬蜥球莖"
  "kumquat tree" = "金橘樹"
  larch = "落葉松"
  leek = "韭蔥"
  "lentil plant" = "扁豆植株"
  "lesser yam plant" = "小山藥植株"
  lettuce = "生菜"
  "lime tree" = "酸橙樹"
  "Longland grass" = "長島草"
  "long yam plant" = "長山藥植株"
  "lychee tree" = "荔枝樹"
  "macadamia tree" = "奶油果樹"
  mahogany = "褐芯樹"
  "maize plant" = "玉米植株"
  "mango tree" = "芒果樹"
  mangrove = "紅樹"
  maple = "楓樹"
  "marsh thistle" = "沼澤薊"
  meadow-grass = "甸草"
  meadowsweet = "繡線菊"
  "mountain avens" = "山薔薇"
  "muck root" = "淤曲根"
  "mung bean plant" = "綠豆植株"
  "muskmelon vine" = "甜瓜藤"
  "needle grass" = "針草"
  nether-cap = "下界菇"
  oak = "橡樹"
  oat = "燕麥"
  "olive tree" = "橄欖樹"
  "onion plant" = "洋蔥植株"
  "orange tree" = "橘子樹"
  "papaya tree" = "番木瓜樹"
  "papyrus sedge" = "紙莎草"
  "paradise nut tree" = "天堂果樹"
  "parsnip plant" = "防風草植株"
  "passion fruit vine" = "百香果藤"
  "peach tree" = "桃樹"
  "peanut plant" = "花生植株"
  "pea plant" = "豌豆植株"
  "pearl millet plant" = "珍珠粟植株"
  "pear tree" = "白梨樹"
  "pebble plant" = "生石花植株"
  "pecan tree" = "碧根果樹"
  "pendant amaranth" = "吊墜莧"
  "pepper plant" = "胡椒植株"
  "persimmon tree" = "柿樹"
  "pig tail" = "豬尾草"
  pine = "針松"
  "pineapple plant" = "菠蘿植株"
  "plump helmet" = "肉盔菇"
  "plum tree" = "李樹"
  "pomegranate tree" = "石榴樹"
  "pomelo tree" = "蜜柚樹"
  "potato plant" = "馬鈴薯植株"
  "prickle berry" = "刺莓"
  "purple amaranth" = "紫莧"
  "purple moor grass" = "紫澤草"
  "purple yam plant" = "紫薯植株"
  "quarry bush" = "礦場灌木"
  quinoa = "藜麥"
  "radish plant" = "小蘿蔔植株"
  "rambutan tree" = "紅毛果樹"
  "ramie plant" = "苧麻植株"
  "raspberry bush" = "樹莓灌木"
  "rat weed" = "雜鼠草"
  "red bean vine" = "紅豆藤"
  "red spinach" = "紅菠菜"
  reedgrass = "茅草"
  rhubarb = "大黃"
  "rice plant" = "稻米植株"
  "rope reed" = "繩索葦"
  "round lime tree" = "圓橘樹"
  "rubber tree" = "橡膠樹"
  rush = "燈心草"
  rye = "黑麥"
  ryegrass = "綠麥草"
  saguaro = "巨刺柱"
  "sand pear tree" = "沙梨樹"
  satintail = "緞尾草"
  sawgrass = "鋸齒草"
  "single-grain wheat" = "單粒小麥"
  "sliver barb" = "裂鉤草"
  "soft wheat" = "軟質小麥"
  sorghum = "高粱"
  "soybean plant" = "黃豆植株"
  spelt = "斯佩爾特麥"
  spinach = "菠菜"
  "spore tree" = "孢子樹"
  "squash vine" = "西葫蘆藤"
  "staring eyeball" = "凝視眼球"
  "strawberry plant" = "草莓植株"
  "string bean plant" = "青豆植株"
  "sun berry" = "太陽漿果"
  "sweet pod" = "甜豆莢"
  "sweet potato plant" = "甘薯植株"
  taro = "芋頭"
  "tea tree" = "茶樹"
  "teff plant" = "苔麩植株"
  "tomatillo plant" = "燈籠番茄植株"
  "tomato plant" = "番茄植株"
  tower-cap = "塔菇"
  "tunnel tube" = "隧管菌"
  "turnip plant" = "蕪菁植株"
  "two-grain wheat" = "雙粒小麥"
  underlichen = "洞窟地衣"
  "urad bean plant" = "尤拉德黑豆植株"
  "valley herb" = "山谷香草"
  "velvet grass" = "絲絨草"
  "walnut tree" = "核桃樹"
  "watermelon vine" = "西瓜藤"
  "whip vine" = "鞭藤"
  "white millet plant" = "白粟植株"
  "white mountain heather" = "白山石楠"
  "white yam plant" = "白薯植株"
  "wild carrot plant" = "野胡蘿蔔植株"
  willow = "柳樹"
  "winter melon vine" = "冬瓜藤"
  "wormy tendril" = "蠕蟲卷鬚"
  zoysia = "結縷草"

[[rulesets]]
name = "plural"

  [rulesets.rules]
  "abaca trees" = "蕉麻樹"
  acacias = "刺槐"
  alders = "榿樹"
  alfalfa = "苜蓿"
  "almond trees" = "扁桃樹"
  "apple trees" = "蘋果樹"
  "apricot trees" = "杏樹"
  "arrow bamboo" = "箭竹"
  artichokes = "洋薊"
  ashes = "白蠟樹"
  asparagus = "蘆筍"
  "avocado trees" = "鱷梨樹"
  "baby toes succulents" = "幼趾多肉"
  "bambara groundnut plants" = "班巴拉花生植株"
  "banana trees" = "香蕉樹"
  barley = "大麥"
  "bayberry trees" = "楊梅樹"
  "beet plants" = "甜菜植株"
  bentgrass = "糠穗草"
  "bilberry bushes" = "越橘灌木"
  birches = "樺樹"
  "bitter melon vines" = "苦瓜藤"
  "bitter orange trees" = "苦橙樹"
  "bitter vetch" = "苦野豌豆"
  "blackberry bushes" = "黑莓灌木"
  black-caps = "黑菇"
  "blade weed" = "刀刃草"
  "bloated tubers" = "膨地根"
  "blood amaranths" = "血莧"
  "blood thorn" = "血荊棘"
  "blueberry bushes" = "藍莓灌木"
  "blue sedge" = "藍苔莎"
  "broad bean plants" = "蠶豆植株"
  "bubble bulbs" = "泡泡球莖"
  buckwheat = "蕎麥"
  cabbages = "捲心菜"
  "cacao trees" = "可可樹"
  candlenuts = "石栗"
  "caper bushes" = "刺山柑灌木"
  "carambola trees" = "楊桃樹"
  carpetgrass = "地毯草"
  "cashew trees" = "腰果樹"
  cassavas = "木薯"
  cattails = "貓尾草"
  "cave moss" = "洞穴苔蘚"
  "cave wheat" = "洞穴小麥"
  cedars = "雪松"
  celery = "芹菜"
  "cherry trees" = "櫻桃樹"
  chestnuts = "板栗樹"
  "chickpea plants" = "鷹嘴豆植株"
  chicory = "菊苣"
  "citron trees" = "香櫞樹"
  cloudberries = "雲莓"
  "coconut palms" = "椰棕櫚"
  "coffee trees" = "咖啡樹"
  "common reeds" = "蘆葦"
  cottongrass = "棉草"
  "cotton plants" = "棉花植株"
  "cowpea plants" = "豇豆植株"
  "cranberry vines" = "蔓越莓藤"
  "cucumber vines" = "黃瓜藤"
  "custard-apple trees" = "番荔枝樹"
  dallisgrass = "雀稗草"
  "date palms" = "棗棕櫚"
  "desert lime trees" = "漠橘樹"
  "dimple cups" = "窩杯菇"
  "dog's tooth grass" = "狗牙草"
  "downy grass" = "羽絨草"
  "dropseed grass" = "落籽草"
  "durian trees" = "榴槤樹"
  eggplants = "茄子"
  "elephant-head amaranths" = "象頭莧"
  "feather trees" = "羽毛樹"
  "fescue grass" = "細葉草"
  "field sedge" = "田野莎草"
  "finger lime trees" = "指橘樹"
  "finger millet plants" = "爪粟植株"
  "fisher berries" = "漁夫漿果"
  "flax plants" = "亞麻植株"
  "floor fungi" = "地真菌"
  "fonio plants" = "非尼奧米植株"
  "foxtail millet plants" = "狐尾粟植株"
  fungiwoods = "真菌木"
  "garden cress" = "水芹"
  "garlic plants" = "大蒜植株"
  "ginkgo trees" = "銀杏樹"
  glumprongs = "紫影樹"
  goblin-caps = "妖精菇"
  "golden bamboo" = "金竹"
  grama = "格蘭馬草"
  "grape vines" = "葡萄藤"
  "guava trees" = "番石榴樹"
  "hair grass" = "發草"
  "hard wheat" = "硬質小麥"
  "hazel trees" = "榛樹"
  "hedge bamboo" = "籬笆竹"
  "hemp plants" = "大麻植株"
  "hide root" = "匿莖草"
  highwoods = "極樹"
  "horned melon vines" = "刺角瓜藤"
  "jute plants" = "黃麻植株"
  kaniwa = "彩藜"
  kapoks = "木棉樹"
  "kenaf plants" = "洋麻植株"
  knotgrass = "繩結草"
  "kobold bulbs" = "犬蜥球莖"
  "kumquat trees" = "金橘樹"
  larches = "落葉松"
  leeks = "韭蔥"
  "lentil plants" = "扁豆植株"
  "lesser yam plants" = "小山藥植株"
  lettuces = "生菜"
  "lime trees" = "酸橙樹"
  "Longland grass" = "長島草"
  "long yam plants" = "長山藥植株"
  "lychee trees" = "荔枝樹"
  "macadamia trees" = "奶油果樹"
  mahoganies = "褐芯樹"
  "maize plants" = "玉米植株"
  "mango trees" = "芒果樹"
  mangroves = "紅樹"
  maples = "楓樹"
  "marsh thistles" = "沼澤薊"
  meadow-grass = "甸草"
  meadowsweet = "繡線菊"
  "mountain avens" = "山薔薇"
  "muck roots" = "淤曲根"
  "mung bean plants" = "綠豆植株"
  "muskmelon vines" = "甜瓜藤"
  "needle grass" = "針草"
  nether-caps = "下界菇"
  oaks = "橡樹"
  oats = "燕麥"
  "olive trees" = "橄欖樹"
  "onion plants" = "洋蔥植株"
  "orange trees" = "橘子樹"
  "papaya trees" = "番木瓜樹"
  "papyrus sedges" = "紙莎草"
  "paradise nut trees" = "天堂果樹"
  "parsnip plants" = "防風草植株"
  "passion fruit vines" = "百香果藤"
  "peach trees" = "桃樹"
  "peanut plants" = "花生植株"
  "pea plants" = "豌豆植株"
  "pearl millet plants" = "珍珠粟植株"
  "pear trees" = "白梨樹"
  "pebble plants" = "生石花植株"
  "pecan trees" = "碧根果樹"
  "pendant amaranths" = "吊墜莧"
  "pepper plants" = "胡椒植株"
  "persimmon trees" = "柿樹"
  "pig tails" = "豬尾草"
  "pineapple plants" = "菠蘿植株"
  pines = "針松"
  "plump helmets" = "肉盔菇"
  "plum trees" = "李樹"
  "pomegranate trees" = "石榴樹"
  "pomelo trees" = "蜜柚樹"
  "potato plants" = "馬鈴薯植株"
  "prickle berries" = "刺莓"
  "purple amaranths" = "紫莧"
  "purple moor grass" = "紫澤草"
  "purple yam plants" = "紫薯植株"
  "quarry bushes" = "礦場灌木"
  quinoa = "藜麥"
  "radish plants" = "小蘿蔔植株"
  "rambutan trees" = "紅毛果樹"
  "ramie plants" = "苧麻植株"
  "raspberry bushes" = "樹莓灌木"
  "rat weed" = "雜鼠草"
  "red bean vines" = "紅豆藤"
  "red spinach" = "紅菠菜"
  reedgrass = "茅草"
  rhubarbs = "大黃"
  "rice plants" = "稻米植株"
  "rope reeds" = "繩索葦"
  "round lime trees" = "圓橘樹"
  "rubber trees" = "橡膠樹"
  rushes = "燈心草"
  rye = "黑麥"
  ryegrass = "綠麥草"
  saguaros = "巨刺柱"
  "sand pear trees" = "沙梨樹"
  satintail = "緞尾草"
  sawgrass = "鋸齒草"
  "single-grain wheat" = "單粒小麥"
  "sliver barbs" = "裂鉤草"
  "soft wheat" = "軟質小麥"
  sorghum = "高粱"
  "soybean plants" = "黃豆植株"
  spelt = "斯佩爾特麥"
  spinach = "菠菜"
  "spore trees" = "孢子樹"
  "squash vines" = "西葫蘆藤"
  "staring eyeballs" = "凝視眼球"
  "strawberry plants" = "草莓植株"
  "string bean plants" = "青豆植株"
  "sun berries" = "太陽漿果"
  "sweet pods" = "甜豆莢"
  "sweet potato plants" = "甘薯植株"
  taro = "芋頭"
  "tea trees" = "茶樹"
  "teff plants" = "苔麩植株"
  "tomatillo plants" = "燈籠番茄植株"
  "tomato plants" = "番茄植株"
  tower-caps = "塔菇"
  "tunnel tubes" = "隧管菌"
  "turnip plants" = "蕪菁植株"
  "two-grain wheat" = "雙粒小麥"
  underlichen = "洞窟地衣"
  "urad bean plants" = "尤拉德黑豆植株"
  "valley herbs" = "山谷香草"
  "velvet grass" = "絲絨草"
  "walnut trees" = "核桃樹"
  "watermelon vines" = "西瓜藤"
  "whip vines" = "鞭藤"
  "white millet plants" = "白粟植株"
  "white mountain heather" = "白山石楠"
  "white yam plants" = "白薯植株"
  "wild carrot plants" = "野胡蘿蔔植株"
  willows = "柳樹"
  "winter melon vines" = "冬瓜藤"
  "wormy tendrils" = "蠕蟲卷鬚"
  zoysia = "結縷草"

[[rulesets]]
name = "adjective"

  [rulesets.rules]
  "abaca tree" = "蕉麻樹"
  acacia = "刺槐"
  alder = "榿樹"
  alfalfa = "苜蓿"
  "almond tree" = "扁桃樹"
  "apple tree" = "蘋果樹"
  "apricot tree" = "杏樹"
  "arrow bamboo" = "箭竹"
  artichoke = "洋薊"
  ashen = "白蠟樹"
  asparagus = "蘆筍"
  "avocado tree" = "鱷梨樹"
  "baby toes succulent" = "幼趾多肉"
  "bambara groundnut plant" = "班巴拉花生植株"
  "banana tree" = "香蕉樹"
  barley = "大麥"
  "bayberry tree" = "楊梅樹"
  "beet plant" = "甜菜植株"
  bentgrass = "糠穗草"
  "bilberry bush" = "越橘灌木"
  birchen = "樺樹"
  "bitter melon vine" = "苦瓜藤"
  "bitter orange tree" = "苦橙樹"
  "bitter vetch" = "苦野豌豆"
  "blackberry bush" = "黑莓灌木"
  black-cap = "黑菇"
  "blade weed" = "刀刃草"
  "bloated tuber" = "膨地根"
  "blood amaranth" = "血莧"
  "blood thorn" = "血荊棘"
  "blueberry bush" = "藍莓灌木"
  "blue sedge" = "藍苔莎"
  "broad bean plant" = "蠶豆植株"
  "bubble bulb" = "泡泡球莖"
  buckwheat = "蕎麥"
  cabbage = "捲心菜"
  "cacao tree" = "可可樹"
  candlenut = "石栗"
  "caper bush" = "刺山柑灌木"
  "carambola tree" = "楊桃樹"
  carpetgrass = "地毯草"
  "cashew tree" = "腰果樹"
  cassava = "木薯"
  cattail = "貓尾草"
  "cave moss" = "洞穴苔蘚"
  "cave wheat" = "洞穴小麥"
  cedar = "雪松"
  celery = "芹菜"
  "cherry tree" = "櫻桃樹"
  chestnut = "板栗樹"
  "chickpea plant" = "鷹嘴豆植株"
  chicory = "菊苣"
  "citron tree" = "香櫞樹"
  cloudberry = "雲莓"
  "coconut palm" = "椰棕櫚"
  "coffee tree" = "咖啡樹"
  "common reed" = "蘆葦"
  cottongrass = "棉草"
  "cotton plant" = "棉花植株"
  "cowpea plant" = "豇豆植株"
  "cranberry vine" = "蔓越莓藤"
  "cucumber vine" = "黃瓜藤"
  "custard-apple tree" = "番荔枝樹"
  dallisgrass = "雀稗草"
  "date palm" = "棗棕櫚"
  "desert lime tree" = "漠橘樹"
  "dimple cup" = "窩杯菇"
  "dog's tooth grass" = "狗牙草"
  "downy grass" = "羽絨草"
  "dropseed grass" = "落籽草"
  "durian tree" = "榴槤樹"
  eggplant = "茄子"
  "elephant-head amaranth" = "象頭莧"
  "feather tree" = "羽毛樹"
  "fescue grass" = "細葉草"
  "field sedge" = "田野莎草"
  "finger lime tree" = "指橘樹"
  "finger millet plant" = "爪粟植株"
  "fisher berry" = "漁夫漿果"
  "flax plant" = "亞麻植株"
  "floor fungus" = "地真菌"
  "fonio plant" = "非尼奧米植株"
  "foxtail millet plant" = "狐尾粟植株"
  fungiwood = "真菌木"
  "garden cress" = "水芹"
  "garlic plant" = "大蒜植株"
  "ginkgo tree" = "銀杏樹"
  glumprong = "紫影樹"
  goblin-cap = "妖精菇"
  "golden bamboo" = "金竹"
  grama = "格蘭馬草"
  "grape vine" = "葡萄藤"
  "guava tree" = "番石榴樹"
  "hair grass" = "發草"
  "hard wheat" = "硬質小麥"
  "hazel tree" = "榛樹"
  "hedge bamboo" = "籬笆竹"
  "hemp plant" = "大麻植株"
  "hide root" = "匿莖草"
  highwood = "極樹"
  "horned melon vine" = "刺角瓜藤"
  "jute plant" = "黃麻植株"
  kaniwa = "彩藜"
  kapok = "木棉樹"
  "kenaf plant" = "洋麻植株"
  knotgrass = "繩結草"
  "kobold bulb" = "犬蜥球莖"
  "kumquat tree" = "金橘樹"
  larch = "落葉松"
  leek = "韭蔥"
  "lentil plant" = "扁豆植株"
  "lesser yam plant" = "小山藥植株"
  lettuce = "生菜"
  "lime tree" = "酸橙樹"
  "Longland grass" = "長島草"
  "long yam plant" = "長山藥植株"
  "lychee tree" = "荔枝樹"
  "macadamia tree" = "奶油果樹"
  mahogany = "褐芯樹"
  "maize plant" = "玉米植株"
  "mango tree" = "芒果樹"
  mangrove = "紅樹"
  maple = "楓樹"
  "marsh thistle" = "沼澤薊"
  meadow-grass = "甸草"
  meadowsweet = "繡線菊"
  "mountain avens" = "山薔薇"
  "muck root" = "淤曲根"
  "mung bean plant" = "綠豆植株"
  "muskmelon vine" = "甜瓜藤"
  "needle grass" = "針草"
  nether-cap = "下界菇"
  oaken = "橡樹"
  oat = "燕麥"
  "olive tree" = "橄欖樹"
  "onion plant" = "洋蔥植株"
  "orange tree" = "橘子樹"
  "papaya tree" = "番木瓜樹"
  "papyrus sedge" = "紙莎草"
  "paradise nut tree" = "天堂果樹"
  "parsnip plant" = "防風草植株"
  "passion fruit vine" = "百香果藤"
  "peach tree" = "桃樹"
  "peanut plant" = "花生植株"
  "pea plant" = "豌豆植株"
  "pearl millet plant" = "珍珠粟植株"
  "pear tree" = "白梨樹"
  "pebble plant" = "生石花植株"
  "pecan tree" = "碧根果樹"
  "pendant amaranth" = "吊墜莧"
  "pepper plant" = "胡椒植株"
  "persimmon tree" = "柿樹"
  "pig tail" = "豬尾草"
  pine = "針松"
  "pineapple plant" = "菠蘿植株"
  "plump helmet" = "肉盔菇"
  "plum tree" = "李樹"
  "pomegranate tree" = "石榴樹"
  "pomelo tree" = "蜜柚樹"
  "potato plant" = "馬鈴薯植株"
  "prickle berry" = "刺莓"
  "purple amaranth" = "紫莧"
  "purple moor grass" = "紫澤草"
  "purple yam plant" = "紫薯植株"
  "quarry bush" = "礦場灌木"
  quinoa = "藜麥"
  "radish plant" = "小蘿蔔植株"
  "rambutan tree" = "紅毛果樹"
  "ramie plant" = "苧麻植株"
  "raspberry bush" = "樹莓灌木"
  "rat weed" = "雜鼠草"
  "red bean vine" = "紅豆藤"
  "red spinach" = "紅菠菜"
  reedgrass = "茅草"
  rhubarb = "大黃"
  "rice plant" = "稻米植株"
  "rope reed" = "繩索葦"
  "round lime tree" = "圓橘樹"
  "rubber tree" = "橡膠樹"
  rush = "燈心草"
  rye = "黑麥"
  ryegrass = "綠麥草"
  saguaro = "巨刺柱"
  "sand pear tree" = "沙梨樹"
  satintail = "緞尾草"
  sawgrass = "鋸齒草"
  "single-grain wheat" = "單粒小麥"
  "sliver barb" = "裂鉤草"
  "soft wheat" = "軟質小麥"
  sorghum = "高粱"
  "soybean plant" = "黃豆植株"
  spelt = "斯佩爾特麥"
  spinach = "菠菜"
  "spore tree" = "孢子樹"
  "squash vine" = "西葫蘆藤"
  "staring eyeball" = "凝視眼球"
  "strawberry plant" = "草莓植株"
  "string bean plant" = "青豆植株"
  "sun berry" = "太陽漿果"
  "sweet pod" = "甜豆莢"
  "sweet potato plant" = "甘薯植株"
  taro = "芋頭"
  "tea tree" = "茶樹"
  "teff plant" = "苔麩植株"
  "tomatillo plant" = "燈籠番茄植株"
  "tomato plant" = "番茄植株"
  tower-cap = "塔菇"
  "tunnel tube" = "隧管菌"
  "turnip plant" = "蕪菁植株"
  "two-grain wheat" = "雙粒小麥"
  underlichen = "洞窟地衣"
  "urad bean plant" = "尤拉德黑豆植株"
  "valley herb" = "山谷香草"
  "velvet grass" = "絲絨草"
  "walnut tree" = "核桃樹"
  "watermelon vine" = "西瓜藤"
  "whip vine" = "鞭藤"
  "white millet plant" = "白粟植株"
  "white mountain heather" = "白山石楠"
  "white yam plant" = "白薯植株"
  "wild carrot plant" = "野胡蘿蔔植株"
  willow = "柳樹"
  "winter melon vine" = "冬瓜藤"
  "wormy tendril" = "蠕蟲卷鬚"
  zoysia = "結縷草"
