base = "visual_ui"

[[rulesets]]
[rulesets.rules]
"{amount}" = "{amount}"
"War, {amount}" = "战争，{amount}"
"{attribute_quality} {creature_attribute}" = "{creature_attribute}{attribute_quality}"
"{plant_tile_first}, {plant_tile_second}" = "{plant_tile_first}，{plant_tile_second}"
"{plant_growth_first}, {plant_growth_second}" = "{plant_growth_first}，{plant_growth_second}"
"{visual_item_first}, {visual_item_second}" = "{visual_item_first}，{visual_item_second}"
Settings = "设定"
Mods = "模组"
Quit = "退出"
Files = "档案"
Folder = "资料夹"
Adventurer = "冒险者"
Fortress = "要塞"
Legends = "传说"
Normal = "正常"
Hard = "困难"
Off = "关闭"
"Enemies:" = "敌人："
"Economy:" = "经济："
Embark = "定居"
"Pickup equipment" = "领取装备"
"Everybody does this" = "所有人执行此项工作"
"Only selected do this" = "仅选中人员执行此项工作"
"Nobody does this" = "无人执行此项工作"
"Add new work detail" = "新增新的工作细则"
Abort = "取消"
Confirm = "确认"
Temperature = "温度"
Spirit = "善恶倾向"
Rain = "降雨量"
Evil = "邪恶"
"X Dimension" = "横向尺寸"
"Y Dimension" = "纵向尺寸"
Drainage = "排水"
Elevation = "海拔"
Savagery = "野性"
Soil = "土壤"
"Neighbors:" = "邻居："
"Aquifer (Light)" = "含水层（轻型）"
"Aquifer (Heavy)" = "含水层（重型）"
Pop = "人口"
Outpost = "前哨站"
"Expedition Leader" = "远征队领队"
"No job" = "无任务"
Healthy = "健康"
Citizen = "公民"
"No official position" = "无官职"
"Squad: None" = "小队：无"
"No unmet needs" = "所有需求均已满足"
"No health problems" = "无健康问题"
"No evaluated wounds" = "无已评估伤势"
"No treatment scheduled" = "未安排治疗"
"No medical history" = "无病史"
"No dedicated workshop assignments" = "未分配专属工坊"
"No location assignments" = "未分配地点"
"Cannot assign work animals" = "无法分配工作动物"
"No assigned or assignable work animals" = "没有已分配或可分配的工作动物"
"No relationships" = "无人际关系"
"No groups" = "无所属团体"
"No squad assigned" = "未分配小队"
Religion = "宗教"
Member = "成员"
Civilization = "文明"
"Site government" = "据点政府"
Kills = "击杀"
Squad = "小队"
Uniform = "制服"
"Poetic form" = "诗歌形式"
Poem = "诗歌"
"Musical form" = "音乐形式"
"Dance form" = "舞蹈形式"
"No Quarters" = "无居所"
"No Study" = "无书房"
"No Dining Room" = "无餐厅"
"No Tomb" = "无墓室"
Status = "状态"
Wounds = "伤势"
Treatment = "治疗"
History = "病史"
Description = "描述"
"Will do available tasks anywhere" = "会在任意地点执行可用任务"
Miners = "矿工"
Woodcutters = "伐木工"
Hunters = "猎人"
Planters = "种植者"
Fisherdwarves = "渔夫"
"Plant gatherers" = "植物采集者"
Stonecutters = "石材切割工"
Engravers = "雕刻工"
Haulers = "搬运工"
Orderlies = "医务勤杂工"
"Siege operators" = "攻城器械操作员"
"{%number} Years Old" = "{%number}岁"
"{%number} Years Old, ♂" = "{%number}岁，♂"
"{%number} Years Old, ♀" = "{%number}岁，♀"
"Downward Slope" = "下坡"
"Shallow Clay" = "浅层黏土"
"Shallow Sand" = "浅层沙地"
"Some soil" = "少量土层"
"Little soil" = "少量土层"
"Deep soil" = "深厚土层"
"Very deep soil" = "极深土层"
"Light aquifer" = "轻型含水层"
"Heavy aquifer" = "重型含水层"
Mountain = "山地"
"Rocky Wasteland" = "岩石荒地"
Badlands = "恶地"
"Sand Desert" = "沙质沙漠"
"Temperate Grassland" = "温带草原"
"Temperate Shrubland" = "温带灌木地"
"Temperate Savanna" = "温带稀树草原"
"Temperate Ocean" = "温带海洋"
"Arctic Ocean" = "极地海洋"
"Main River" = "主要河流"
"Main River:" = "主要河流："
"Minor River" = "次要河流"
"Minor River:" = "次要河流："
"Temperate Freshwater Marsh" = "温带淡水沼泽"
"Temperate Saltwater Marsh" = "温带咸水沼泽"
"Temperate Brackish Lake" = "温带半咸水湖"
"Temperate Conifer Forest" = "温带针叶林"
"Temperate Freshwater Lake" = "温带淡水湖"
"Tropical Dry Brdlf Forest" = "热带干燥阔叶林"
"Tropical Moist Brdlf Forst" = "热带湿润阔叶林"
"Tropical Coniferous Forest" = "热带针叶林"
"Tropical Freshwater Lake" = "热带淡水湖"
"Tropical Freshwater Marsh" = "热带淡水沼泽"
"Tropical Freshwater Swamp" = "热带淡水森林沼泽"
"Tropical Brackish Lake" = "热带半咸水湖"
"Tropical Ocean" = "热带海洋"
"Tropical Saltwater Marsh" = "热带咸水沼泽"
"Tropical Saltwater Swamp" = "热带咸水森林沼泽"
"Tropical Grassland" = "热带草原"
"Tropical Savanna" = "热带稀树草原"
"Tropical Shrubland" = "热带灌木地"

[[rulesets]]
name = "direction"

  [rulesets.rules]
  north = "向北"
  south = "向南"
  east = "向东"
  west = "向西"
  NE = "向东北"
  NW = "向西北"
  SE = "向东南"
  SW = "向西南"

[[rulesets]]
name = "distance"

  [rulesets.rules]
  "A short trip" = "短途可达"
  "A day's travel" = "行程1天"
  "1/2 day's travel" = "行程半天"
  "2 days' travel" = "行程2天"
  "3 days' travel" = "行程3天"

[[rulesets]]
name = "amount"

  [rulesets.rules]
  hundred = "一百"
  hundreds = "数百"
  "a few hundred" = "几百"
  "a thousand" = "一千"
  "two thousand" = "两千"
  "three thousand" = "三千"
  "four thousand" = "四千"
  "five thousand" = "五千"

[[rulesets]]
name = "trees"

  [rulesets.rules]
  None = "无"
  Scarce = "稀少"
  Sparse = "稀疏"
  Woodland = "林地"
  "Heavily Forested" = "森林茂密"

[[rulesets]]
name = "vegetation"

  [rulesets.rules]
  None = "无"
  Scarce = "稀少"
  Moderate = "中等"
  Thick = "茂密"

[[rulesets]]
name = "surroundings"

  [rulesets.rules]
  Calm = "平静"
  Wilderness = "荒野"
  "Untamed Wilds" = "未驯荒野"
  Sinister = "阴森"

[[rulesets]]
name = "temperature"

  [rulesets.rules]
  Cold = "寒冷"
  Temperate = "温和"
  Warm = "温暖"
  Hot = "炎热"
  Scorching = "酷热"

[[rulesets]]
name = "attribute_quality"

  [rulesets.rules]
  "Very poor" = "极差"
  Poor = "较差"
  "Below average" = "低于平均"
  Average = "一般"
  "Above average" = "高于平均"
  Good = "良好"
  "Very good" = "很好"
  Great = "出色"
  Exceptional = "非凡"

[[rulesets]]
name = "creature_attribute"

  [rulesets.rules]
  strength = "力量"
  agility = "敏捷"
  toughness = "坚韧"
  endurance = "耐力"
  recuperation = "恢复能力"
  "disease resistance" = "抗病能力"
  "analytical ability" = "分析能力"
  focus = "专注力"
  willpower = "意志力"
  creativity = "创造力"
  intuition = "直觉"
  patience = "耐心"
  memory = "记忆力"
  "linguistic ability" = "语言能力"
  "spatial sense" = "空间感"
  musicality = "乐感"
  "kinesthetic sense" = "运动感知"
  empathy = "同理心"
  "social awareness" = "社会意识"

[[rulesets]]
name = "historical_creature"

  [rulesets.rules]
  dwarf = "矮人"
  elf = "精灵"
  human = "人类"
  goblin = "哥布林"

[[rulesets]]
name = "historical_position"

  [rulesets.rules]
  druid = "德鲁伊"
  king = "国王"
  queen = "女王"
  law-giver = "立法者"
  master = "首领"
  chancellor = "大臣"
  "high treasurer" = "财政大臣"
  justiciar = "司法官"
  "keeper of the seal" = "掌玺官"
  "master of beasts" = "兽群主管"
  "royal advisor" = "王室顾问"
  "royal chamberlain" = "王室内务官"
  "royal executioner" = "王室刽子手"

[[rulesets]]
name = "historical_season"

  [rulesets.rules]
  "early spring" = "初春"
  midspring = "仲春"
  "late spring" = "暮春"
  "early summer" = "初夏"
  midsummer = "仲夏"
  "late summer" = "暮夏"
  "early autumn" = "初秋"
  midautumn = "仲秋"
  "late autumn" = "暮秋"
  "early winter" = "初冬"
  midwinter = "仲冬"
  "late winter" = "暮冬"

[[rulesets]]
name = "visual_item_first"

  [rulesets.rules]
  "{::items}" = "{::items}"

[[rulesets]]
name = "visual_item_second"

  [rulesets.rules]
  "{::items}" = "{::items}"

[[rulesets]]
name = "plant_growth_first"

  [rulesets.rules]
  "{::items::plant_growth}" = "{::items::plant_growth}"

[[rulesets]]
name = "plant_growth_second"

  [rulesets.rules]
  "{::items::plant_growth}" = "{::items::plant_growth}"

[[rulesets]]
name = "plant_tile_first"

  [rulesets.rules]
  "{::tiles::plants}" = "{::tiles::plants}"

[[rulesets]]
name = "plant_tile_second"

  [rulesets.rules]
  "{::tiles::plants}" = "{::tiles::plants}"
